import {cp,mkdir,readFile,readdir,rename,rm,stat,writeFile} from "node:fs/promises";
import {dirname,join,relative,resolve} from "node:path";

export const MANIFEST_FILES=Object.freeze(["data/solar-system/ephemeris-manifest.json","data/solar-system/small-body-manifest.json","data/solar-system/tno-manifest.json","data/solar-system/comet-manifest.json"]);
export const NORMALIZED_FILES=Object.freeze(["data/solar-system/normalized/major-bodies-horizons-de441.js","data/solar-system/normalized/small-bodies-sbdb.js","data/solar-system/normalized/tno-sbdb.js","data/solar-system/normalized/comets-sbdb.js"]);
export const VALIDATION_FILES=Object.freeze(["test-results/solar-system-ss02b/authoritative-position-comparison.json","test-results/solar-system-ss02c/authoritative-position-comparison.json","test-results/solar-system-ss02d/authoritative-position-comparison.json","test-results/solar-system-ss02e/authoritative-position-comparison.json","test-results/solar-system-ss02f/meteor-shower-validation.json"]);

export async function loadValidatedManifests(appRoot){const entries=[];for(const file of MANIFEST_FILES){const value=JSON.parse(await readFile(resolve(appRoot,file),"utf8"));if(value.promotionStatus!=="validated-promoted"||value.validation?.failures!==0)throw new Error(`${file} is not validated-promoted`);entries.push(Object.freeze({file,datasetId:value.datasetId,lastSuccessfulSynchronization:value.lastSuccessfulSynchronization,validatedAt:value.validatedAt,source:value.source,recordCount:value.recordCount??value.mainBeltRecordCount??value.objects?.length??null,validationComparisons:value.validation.comparisonCount}));}return Object.freeze(entries);}
export function buildSyncStatus({manifests,generatedAt,state="validated",previous=null,error=null,lastSuccessfulSynchronization=null}){const successfulAt=state==="validated"?(lastSuccessfulSynchronization||generatedAt):(previous?.lastSuccessfulSynchronization||manifests.map(item=>item.lastSuccessfulSynchronization).filter(Boolean).sort().at(-1)||null);return Object.freeze({schemaVersion:1,pipelineId:"pcs-solar-system-ss02f",generatedAt,state,lastSuccessfulSynchronization:successfulAt,failedAt:state==="stale"?generatedAt:null,lastError:error?String(error).slice(0,500):null,updatePolicy:"Periodic catalog synchronization",fallbackPolicy:"Retain last validated deployed artifacts when ingestion or validation fails",datasets:manifests});}
export async function writeSyncStatus(appRoot,status){const json=`${JSON.stringify(status,null,2)}\n`,js=`(function(g){"use strict";g.PCSSolarSystemSyncStatus=Object.freeze(${JSON.stringify(status)});})(window);\n`;await mkdir(resolve(appRoot,"data/solar-system/normalized"),{recursive:true});await writeFile(resolve(appRoot,"data/solar-system/sync-status.json"),json);await writeFile(resolve(appRoot,"data/solar-system/normalized/sync-status.js"),js);}
export async function atomicPromoteFile(source,target){await mkdir(dirname(target),{recursive:true});const temporary=`${target}.pcs-candidate-${process.pid}`;await cp(source,temporary,{force:true});await rename(temporary,target);}
export async function listFiles(root){const files=[];async function visit(directory){for(const entry of await readdir(directory,{withFileTypes:true})){const path=join(directory,entry.name);if(entry.isDirectory())await visit(path);else if(entry.isFile())files.push(relative(root,path));}}try{if((await stat(root)).isDirectory())await visit(root);}catch(error){if(error.code!=="ENOENT")throw error;}return files.sort();}
export async function promoteValidatedFiles(candidateRoot,deployedRoot,files){
  const suffix=`pcs-${process.pid}`,operations=[];
  try{
    // Stage every candidate before touching the deployed set. A missing or unreadable
    // candidate therefore leaves the complete last-validated deployment unchanged.
    for(const file of files){const source=resolve(candidateRoot,file),target=resolve(deployedRoot,file),staged=`${target}.${suffix}-candidate`,backup=`${target}.${suffix}-backup`;await mkdir(dirname(target),{recursive:true});await cp(source,staged,{force:true});operations.push({target,staged,backup,hadTarget:false,installed:false});}
    // Swap only after the full set is staged. If any swap fails, reverse every prior
    // swap so manifests, normalized data, evidence, and raw snapshots stay coherent.
    for(const operation of operations){try{await rename(operation.target,operation.backup);operation.hadTarget=true;}catch(error){if(error.code!=="ENOENT")throw error;}await rename(operation.staged,operation.target);operation.installed=true;}
    await Promise.all(operations.filter(item=>item.hadTarget).map(item=>rm(item.backup,{force:true})));
  }catch(error){for(const operation of [...operations].reverse()){if(operation.installed)await rm(operation.target,{force:true});if(operation.hadTarget)await rename(operation.backup,operation.target).catch(()=>{});await rm(operation.staged,{force:true}).catch(()=>{});}throw error;}
  return files.length;
}
export async function promoteValidatedCandidate(candidateRoot,deployedRoot){const raw=(await listFiles(resolve(candidateRoot,"data/solar-system/raw"))).map(file=>`data/solar-system/raw/${file}`),files=[...new Set([...MANIFEST_FILES,...NORMALIZED_FILES,...VALIDATION_FILES,"data/solar-system/sync-status.json","data/solar-system/normalized/sync-status.js",...raw])];const filesPromoted=await promoteValidatedFiles(candidateRoot,deployedRoot,files);return Object.freeze({filesPromoted,rawSnapshots:raw.length});}
