import {createHash} from "node:crypto";
import {gzipSync} from "node:zlib";
import {mkdir,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {buildCometLookupQuery,normalizeCometLookupResponse} from "./sbdb-adapter.mjs";
import {buildVectorQuery,normalizeResponse as normalizeHorizonsResponse} from "./horizons-adapter.mjs";

const here=dirname(fileURLToPath(import.meta.url)),appRoot=resolve(here,"../.."),rawRoot=resolve(appRoot,"data/solar-system/raw/sbdb"),normalizedRoot=resolve(appRoot,"data/solar-system/normalized");
const designations=Object.freeze(["1P","2P","8P","21P","55P","67P","96P","109P","C/1861 G1"]),generatedAt=new Date().toISOString(),generatedJd=Date.parse(generatedAt)/86400000+2440587.5,raw=[],cometEphemeris=[],steps=Object.freeze({"21P":"1 d"});
for(const designation of designations){const url=buildCometLookupQuery(designation),response=await fetch(url,{headers:{accept:"application/json","user-agent":"PCS-Observatory-SS02/2.2"}});if(!response.ok)throw new Error(`${designation}: SBDB HTTP ${response.status}`);const payload=await response.json(),record=normalizeCometLookupResponse(payload),normalized={...record,nextPerihelionTdb:Number.isFinite(record.elements.tp)&&record.elements.tp>generatedJd?record.perihelionCalendarTdb:null},step=steps[designation]||"3 d";raw.push({designation,url,payload,record:normalized});const request=buildVectorQuery({command:`DES=${record.designation};CAP;NOFRAG`,center:"500@10",start:"2025-01-01",stop:"2028-01-01",step}),vectorResponse=await fetch(request.url,{headers:{accept:"application/json","user-agent":"PCS-Observatory-SS02/2.2"}});if(!vectorResponse.ok)throw new Error(`${designation}: Horizons HTTP ${vectorResponse.status}`);const vectorText=await vectorResponse.text(),vectors=normalizeHorizonsResponse(JSON.parse(vectorText),request,{objectId:record.spkid,naifId:record.spkid,retrievedAt:generatedAt});raw.at(-1).horizons={url:request.url,payload:JSON.parse(vectorText)};cometEphemeris.push({spkid:record.spkid,designation:record.designation,name:record.name,source:vectors.source,catalogEphemeris:vectors.catalogEphemeris,centerName:vectors.centerName,step,command:request.command,samples:vectors.samples.map(sample=>[sample.jdTdb,...sample.positionAu,...sample.velocityAuPerDay])});}
const records=raw.map(item=>item.record),required=["e","a","q","i","om","w","ma","tp","epochJdTdb","periodDays"],invalid=records.filter(record=>!required.every(key=>Number.isFinite(record.elements[key]))||record.elements.e<0||record.elements.e>=1);if(invalid.length)throw new Error(`Unsupported comet elements: ${invalid.map(x=>x.designation).join(", ")}`);
await mkdir(rawRoot,{recursive:true});await mkdir(normalizedRoot,{recursive:true});const rawText=JSON.stringify({generatedAt,requests:raw.map(({designation,url,payload})=>({designation,url,payload}))});await writeFile(resolve(rawRoot,"priority-comets.json.gz"),gzipSync(rawText,{level:9}));
const dataset={schemaVersion:1,datasetId:"pcs-ss02e-sbdb-priority-comets",generatedAt,source:"NASA/JPL SBDB and Horizons APIs",sourceUrl:"https://ssd-api.jpl.nasa.gov/doc/sbdb.html",selection:{type:"curated priority periodic/scientifically important comet subset",designations,deterministic:true,completeCatalog:false},recordCount:records.length,positionMode:"Cached Horizons vectors · cubic Hermite state; SBDB element fallback is disclosed two-body propagation",referenceFrame:"ICRF; Earth mean ecliptic at J2000.0; heliocentric origin",fallbackPolicy:"Retain last validated catalog; do not fabricate a missing orbit solution.",cometEphemeris:{coverage:{start:"2025-01-01T00:00:00.000Z",end:"2028-01-01T00:00:00.000Z"},interpolation:"Cubic Hermite using Horizons position and velocity",records:cometEphemeris},records};
const js=`(function(g){"use strict";g.PCSSolarSystemCometDataset=Object.freeze(${JSON.stringify(dataset)});})(window);\n`,sha256=value=>createHash("sha256").update(value).digest("hex");await writeFile(resolve(normalizedRoot,"comets-sbdb.js"),js);
const manifest={schemaVersion:1,datasetId:dataset.datasetId,promotionStatus:"candidate",generatedAt,lastSuccessfulSynchronization:generatedAt,source:dataset.source,sourceUrl:dataset.sourceUrl,selection:dataset.selection,recordCount:records.length,rawFile:"raw/sbdb/priority-comets.json.gz",rawSha256:sha256(rawText),normalizedFile:"normalized/comets-sbdb.js",normalizedSha256:sha256(js),fallbackPolicy:dataset.fallbackPolicy};await writeFile(resolve(appRoot,"data/solar-system/comet-manifest.json"),`${JSON.stringify(manifest,null,2)}\n`);console.log(`Comets: ${records.length} priority records synchronized`);
