import {readFile,mkdir,writeFile} from "node:fs/promises";
import {resolve,dirname} from "node:path";
import {fileURLToPath} from "node:url";
import vm from "node:vm";
import {buildVectorQuery,normalizeResponse} from "./horizons-adapter.mjs";

const here=dirname(fileURLToPath(import.meta.url)),appRoot=resolve(here,"../.."),window={};for(const name of ["solar-system-core.js","data/solar-system/normalized/small-bodies-sbdb.js","data/solar-system/normalized/comets-sbdb.js","small-body-catalog.js"])vm.runInNewContext(await readFile(resolve(appRoot,name),"utf8"),{window,Date,Math,RangeError,Object,Map,Number,String,Boolean,Infinity});
const Core=window.PCSSolarSystemCore,Small=window.PCSSmallBodies,dataset=window.PCSSolarSystemCometDataset,AU_KM=149597870.7,tolerancesKm=Object.freeze({"1P":0.5,"2P":2,"8P":0.5,"21P":1,"55P":0.5,"67P":1,"96P":0.5,"109P":0.5,"1861 G1":0.5}),comparisons=[];
async function compare(record,epochUtc){const state=Small.stateAt(record,epochUtc),command=`DES=${record.designation};CAP;NOFRAG`,request=buildVectorQuery({command,center:"500@10",start:`JD${state.jdTdb.toFixed(9)}`,stop:`JD${(state.jdTdb+1/144).toFixed(9)}`,step:"10 m"}),response=await fetch(request.url,{headers:{accept:"application/json","user-agent":"PCS-Observatory-SS02-Validation/2.2"}});if(!response.ok)throw new Error(`${record.designation}: Horizons HTTP ${response.status}`);const reference=normalizeResponse(await response.json(),request,{objectId:record.spkid,naifId:record.spkid,retrievedAt:new Date().toISOString()}).samples[0],differenceKm=Math.hypot(...state.positionAu.map((value,index)=>(value-reference.positionAu[index])*AU_KM)),toleranceKm=tolerancesKm[record.designation],cadence=dataset.cometEphemeris.records.find(item=>item.spkid===record.spkid)?.step,item={epochUtc,jdTdb:state.jdTdb,object:record.name,designation:record.designation,spkid:record.spkid,objectClass:"priority comet",referenceSource:"NASA/JPL Horizons direct VECTORS query",referenceCommand:command,pcsPositionAu:state.positionAu,referencePositionAu:reference.positionAu,difference:differenceKm,units:"km",tolerance:toleranceKm,toleranceBasis:`Object-specific cubic-Hermite ceiling for the deployed ${cadence} ${record.designation} cache, selected after withheld-epoch measurement; not observational uncertainty.`,positionMode:state.positionMode,pass:differenceKm<=toleranceKm};comparisons.push(item);console.log(`${record.designation} ${epochUtc}: ${differenceKm.toFixed(6)} km / ${toleranceKm} km`);}
for(const record of dataset.records)for(const epoch of ["2025-04-17T06:17:00Z","2026-08-08T12:41:00Z"])await compare(record,epoch);
const failures=comparisons.filter(item=>!item.pass),report={schemaVersion:1,stage:"SS-02E",generatedAt:new Date().toISOString(),datasetId:dataset.datasetId,method:"Independent direct Horizons comet vectors versus promoted cached-vector cubic-Hermite state.",comparisonCount:comparisons.length,pass:failures.length===0,failures:failures.length,comparisons},output=resolve(appRoot,"test-results/solar-system-ss02e/authoritative-position-comparison.json");await mkdir(dirname(output),{recursive:true});await writeFile(output,`${JSON.stringify(report,null,2)}\n`);if(failures.length)throw new Error(`${failures.length} SS-02E comparisons failed`);
const manifestPath=resolve(appRoot,"data/solar-system/comet-manifest.json"),manifest=JSON.parse(await readFile(manifestPath,"utf8"));manifest.promotionStatus="validated-promoted";manifest.validatedAt=report.generatedAt;manifest.validation={comparisonCount:report.comparisonCount,failures:0,evidence:"../../test-results/solar-system-ss02e/authoritative-position-comparison.json",tolerancePolicy:"Per-comet withheld-epoch cubic-Hermite ceilings for each deployed object cadence (one or three days); not observational uncertainty and not a universal small-body tolerance."};await writeFile(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);console.log(`SS-02E authoritative comparison: PASS (${comparisons.length})`);
