const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
function runtime(){const context={globalThis:null};context.globalThis=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,"astronomical-camera-scale.js"),"utf8"),context);return context.PCSAstronomicalCameraScale;}

test("astronomical scale classification is distance-based with an explicit comet-orbit intent",()=>{const scale=runtime();assert.equal(scale.classify({distanceAu:.001}),"PLANETARY");assert.equal(scale.classify({distanceAu:1}),"INNER SOLAR SYSTEM");assert.equal(scale.classify({distanceAu:35}),"SOLAR SYSTEM");assert.equal(scale.classify({distanceAu:100}),"HELIOSPHERE");assert.equal(scale.classify({distanceAu:1000}),"INTERSTELLAR");assert.equal(scale.classify({context:"milky-way",distanceAu:0}),"MILKY WAY");assert.equal(scale.classify({distanceAu:35,intent:"comet-orbit"}),"COMET ORBIT");});

test("Milky Way subscales stay inside the shared astronomical camera architecture",()=>{const scale=runtime();assert.equal(scale.classify({context:"milky-way",intent:"solar-neighborhood"}),"SOLAR NEIGHBORHOOD");assert.equal(scale.classify({context:"milky-way",intent:"local-arm"}),"LOCAL ARM");assert.equal(scale.classify({context:"milky-way",intent:"galactic-disk"}),"GALACTIC DISK");assert.equal(scale.classify({context:"milky-way",intent:"whole-milky-way"}),"MILKY WAY");assert.equal(scale.classify({context:"milky-way",distanceKpc:.1}),"SOLAR NEIGHBORHOOD");assert.equal(scale.classify({context:"milky-way",distanceKpc:2}),"LOCAL ARM");assert.equal(scale.classify({context:"milky-way",distanceKpc:18}),"GALACTIC DISK");assert.equal(scale.classify({context:"milky-way",distanceKpc:70}),"MILKY WAY");});

test("bounding sphere encloses a complete asymmetric orbit",()=>{const scale=runtime(),points=[[-1,0,0],[35,0,0],[0,2,0],[0,-2,0]],sphere=scale.boundingSphere(points);assert.deepEqual(Array.from(sphere.center),[17,0,0]);for(const point of points)assert.ok(Math.hypot(...point.map((value,index)=>value-sphere.center[index]))<=sphere.radius+1e-12);assert.equal(sphere.pointCount,4);});

test("fit distance responds to actual aspect ratio rather than display pixel presets",()=>{const scale=runtime(),wide=scale.fitDistance({radius:10,fovY:Math.PI/3,aspectRatio:21/9}),standard=scale.fitDistance({radius:10,fovY:Math.PI/3,aspectRatio:16/9}),portrait=scale.fitDistance({radius:10,fovY:Math.PI/3,aspectRatio:9/16});assert.ok(Math.abs(wide-standard)<1e-12,"vertical FOV limits both wide desktop viewports");assert.ok(portrait>standard,"narrow viewport requires more camera range");assert.ok(scale.clipPlanes({range:standard,radius:10}).far>standard+10);});

test("fit distance permits a bounded close fit for the human-reviewed Milky Way viewport",()=>{const scale=runtime(),normal=scale.fitDistance({radius:100,fovY:Math.PI/3,aspectRatio:1.5,margin:1}),close=scale.fitDistance({radius:100,fovY:Math.PI/3,aspectRatio:1.5,margin:.94}),clamped=scale.fitDistance({radius:100,fovY:Math.PI/3,aspectRatio:1.5,margin:.1});assert.ok(close<normal);assert.ok(clamped<close);assert.ok(clamped>0);});

test("orbit plane is stable and normalized",()=>{const scale=runtime(),plane=scale.orbitPlane([[1,0,0],[0,2,0],[-1,0,0],[0,-2,0]],[0,0,0]);assert.ok(Math.abs(Math.hypot(...plane.normal)-1)<1e-12);assert.ok(Math.abs(Math.hypot(...plane.up)-1)<1e-12);assert.ok(Math.abs(plane.normal[2])>.999);});
