(function exposeDeepSpaceManager(global) {
  "use strict";
  const DS = global.PCSDeepSpaceRegistry;
  const Eph = global.PCSDeepSpaceEphemeris;
  const Nearby = global.PCSNearbyStars;
  const MilkyWay = global.PCSMilkyWay;
  const LocalGroup = global.PCSLocalGroup;
  const Coordinates = global.PCSPhase3Coordinates;
  const PointerNavigation = global.PCSPointerAnchoredNavigation;
  const ObjectCard = global.PCSUnifiedObjectCard;
  const SolarCore = global.PCSSolarSystemCore;
  const SmallBodies = global.PCSSmallBodies;
  if (!DS || !Eph || !Nearby || !MilkyWay || !LocalGroup || !PointerNavigation || !ObjectCard || !SolarCore || !SmallBodies) return;

  const COPY = {
    en:{title:"PCS DEEP SPACE",scale:"Scale",time:"Time",objects:"Objects",orbits:"Orbits",labels:"Labels",data:"Data",dwarfPlanets:"Dwarf Planets",mainBelt:"Main Belt catalog subset",close:"Close Deep Space",reset:"Reset view",earth:"Return to Earth",solar:"Return to Solar System",follow:"Follow selected body",top:"Top view",inclined:"Inclined view",scientific:"Scientific Scale",exhibition:"Exhibition Scale",play:"Play",pause:"Pause",now:"Reset to now",phase2:"Nearby Stars — Available in Phase 2",noticeEx:"Exhibition scale — Distances visually compressed — Not a single linear scale",noticeSci:"Scientific scale — radii and distances use the same linear kilometre scale",ephemeris:"Ephemeris-based orbital visualization",approx:"Orbital-element approximation — Not mission-navigation precision",collapse:"Collapse controls",expand:"Expand controls",retry:"Retry",cached:"Use cached ephemeris",fallback:"Use orbital approximation",later:"Available in a later phase"},
    "zh-TW":{title:"PCS 深空",scale:"尺度",time:"時間",objects:"天體",orbits:"軌道",labels:"標籤",data:"資料",dwarfPlanets:"矮行星",mainBelt:"主小行星帶星表子集",close:"關閉深空",reset:"重設視角",earth:"返回地球",solar:"返回太陽系",follow:"跟隨所選天體",top:"俯視",inclined:"傾斜視角",scientific:"科學比例",exhibition:"展演比例",play:"播放",pause:"暫停",now:"重設為現在",phase2:"鄰近恆星 — Phase 2 開放",noticeEx:"展演比例 — 距離經視覺壓縮 — 並非單一線性比例",noticeSci:"科學比例 — 半徑與距離採用相同公里線性比例",ephemeris:"基於星曆的軌道視覺化",approx:"軌道元素近似 — 非任務導航精度",collapse:"收合控制列",expand:"展開控制列",retry:"重試",cached:"使用快取星曆",fallback:"使用軌道近似",later:"後續階段開放"},
    ja:{title:"PCS ディープスペース",scale:"スケール",time:"時間",objects:"天体",orbits:"軌道",labels:"ラベル",data:"データ",dwarfPlanets:"準惑星",mainBelt:"メインベルト・カタログ部分集合",close:"閉じる",reset:"ビューをリセット",earth:"地球へ戻る",solar:"太陽系へ戻る",follow:"選択天体を追跡",top:"トップビュー",inclined:"傾斜ビュー",scientific:"科学スケール",exhibition:"展示スケール",play:"再生",pause:"一時停止",now:"現在に戻す",phase2:"近傍恒星 — Phase 2で利用可能",noticeEx:"展示スケール — 距離を視覚的に圧縮 — 単一線形スケールではありません",noticeSci:"科学スケール — 半径と距離は同一のkm線形比率",ephemeris:"暦に基づく軌道可視化",approx:"軌道要素による近似 — 航法精度ではありません",collapse:"操作を折りたたむ",expand:"操作を展開",retry:"再試行",cached:"キャッシュ暦を使用",fallback:"軌道近似を使用",later:"今後のフェーズで利用可能"},
    ko:{title:"PCS 딥 스페이스",scale:"축척",time:"시간",objects:"천체",orbits:"궤도",labels:"레이블",data:"데이터",dwarfPlanets:"왜행성",mainBelt:"주 소행성대 카탈로그 부분집합",close:"딥 스페이스 닫기",reset:"보기 초기화",earth:"지구로 돌아가기",solar:"태양계로 돌아가기",follow:"선택 천체 추적",top:"평면 보기",inclined:"경사 보기",scientific:"과학 축척",exhibition:"전시 축척",play:"재생",pause:"일시정지",now:"현재로 재설정",phase2:"인접 항성 — Phase 2에서 제공",noticeEx:"전시 축척 — 거리를 시각적으로 압축 — 단일 선형 축척 아님",noticeSci:"과학 축척 — 반지름과 거리에 동일한 km 선형 축척 사용",ephemeris:"천체력 기반 궤도 시각화",approx:"궤도 요소 근사 — 임무 항법 정밀도 아님",collapse:"컨트롤 접기",expand:"컨트롤 펼치기",retry:"다시 시도",cached:"캐시 천체력 사용",fallback:"궤도 근사 사용",later:"추후 단계에서 제공"},
  };
  const SPEEDS = Object.freeze({"1×":1,"60×":60,"1 hour / second":3600,"1 day / second":86400,"30 days / second":2592000});
  const CONNECTIVITY = Object.freeze({
    en:{online:"Online — deployed validated datasets remain the runtime source",offline:"Offline — deployed validated datasets and documented fallback remain available"},
    "zh-TW":{online:"已連線 — runtime 仍使用已部署且驗證的資料集",offline:"離線模式 — 已部署的驗證資料集與有文件的 fallback 仍可使用"},
    ja:{online:"オンライン — ランタイムは配備済みの検証済みデータセットを使用",offline:"オフライン — 配備済みデータセットと文書化されたフォールバックを利用可能"},
    ko:{online:"온라인 — 런타임은 배포·검증된 데이터셋을 사용",offline:"오프라인 — 배포된 검증 데이터셋과 문서화된 대체 모델 사용 가능"},
  });
  const NEAR_COPY=Object.freeze({
    en:{nearby:"Nearby Stars",neighborhood:"Solar Neighborhood",distance:"Distance",parallax:"Parallax",proper:"Proper motion",radial:"Radial velocity",reference:"Reference epoch",quality:"Data quality",catalog:"Catalog",search:"Search",notFound:"No deployed catalog result found",phase3:"Milky Way — Available in Phase 3",marker:"Star marker size is visually enhanced. Not to physical stellar-radius scale.",frame:"Coordinate frame",loading:"Loading local Gaia catalog…",reduced:"Use reduced catalog",motion:"Proper motion analysis",guides:"Distance spheres / axes",unavailable:"Unavailable",incomplete:"Incomplete",retry:"Retry",returnSolar:"Return to Solar System",close:"Close Deep Space",analysisYear:"Comparison year",propagation:"Linear astrometric propagation; supported window ±100 years from reference epoch.",windowWarning:"Outside ±100 years; display clamped to the supported analysis window.",legend:"Quality legend",loadError:"Catalog loading failed"},
    "zh-TW":{nearby:"鄰近恆星",neighborhood:"太陽鄰域",distance:"距離",parallax:"視差",proper:"自行",radial:"徑向速度",reference:"參考曆元",quality:"資料品質",catalog:"星表",search:"搜尋",notFound:"本地部署星表中找不到結果",phase3:"銀河系 — Phase 3 開放",marker:"恆星標記尺寸經視覺增強，並非恆星實體半徑比例。",frame:"座標框架",loading:"正在載入本地 Gaia 星表…",reduced:"使用精簡星表",motion:"自行分析",guides:"距離球／座標軸",unavailable:"無資料",incomplete:"不完整",retry:"重試",returnSolar:"返回太陽系",close:"關閉深空",analysisYear:"比較年份",propagation:"線性天體測量推進；支援範圍為參考曆元前後 100 年。",windowWarning:"超出前後 100 年範圍；顯示已限制於支援的分析窗口。",legend:"品質圖例",loadError:"星表載入失敗"},
    ja:{nearby:"近傍恒星",neighborhood:"太陽近傍",distance:"距離",parallax:"年周視差",proper:"固有運動",radial:"視線速度",reference:"基準元期",quality:"データ品質",catalog:"カタログ",search:"検索",notFound:"配備済みカタログに結果がありません",phase3:"天の川銀河 — Phase 3で利用可能",marker:"恒星マーカーは視認性のため拡大されています。実半径スケールではありません。",frame:"座標系",loading:"ローカルGaiaカタログを読み込み中…",reduced:"縮小カタログを使用",motion:"固有運動解析",guides:"距離球／座標軸",unavailable:"利用不可",incomplete:"不完全",retry:"再試行",returnSolar:"太陽系へ戻る",close:"ディープスペースを閉じる",analysisYear:"比較年",propagation:"線形アストロメトリ伝播。基準元期から±100年をサポートします。",windowWarning:"±100年の範囲外です。表示はサポート範囲に制限されます。",legend:"品質凡例",loadError:"カタログの読み込みに失敗しました"},
    ko:{nearby:"인접 항성",neighborhood:"태양 근방",distance:"거리",parallax:"시차",proper:"고유 운동",radial:"시선 속도",reference:"기준 역기점",quality:"데이터 품질",catalog:"카탈로그",search:"검색",notFound:"배포된 로컬 카탈로그에 결과가 없습니다",phase3:"은하수 — Phase 3에서 제공",marker:"항성 마커 크기는 시각적으로 확대되었으며 실제 항성 반지름 축척이 아닙니다.",frame:"좌표계",loading:"로컬 Gaia 카탈로그 로드 중…",reduced:"축소 카탈로그 사용",motion:"고유 운동 분석",guides:"거리 구／좌표축",unavailable:"사용 불가",incomplete:"불완전",retry:"다시 시도",returnSolar:"태양계로 돌아가기",close:"딥 스페이스 닫기",analysisYear:"비교 연도",propagation:"선형 측성 전파이며 기준 역기점에서 ±100년을 지원합니다.",windowWarning:"±100년 범위를 벗어나 표시가 지원 분석 창으로 제한됩니다.",legend:"품질 범례",loadError:"카탈로그 로드 실패"}
  });
  const PHASE3_COPY=Object.freeze({
    en:{phase3:"Phase 3",milkyWay:"Milky Way",galacticCenter:"Galactic Center",sagittarius:"Sagittarius A*",galacticDisk:"Galactic disk",galacticBar:"Galactic bar",spiralArms:"Spiral arms",magellanic:"Magellanic System",localGroup:"Local Group",search:"Search",searchLabel:"Phase 3 catalog search",labels:"Labels",reconstruction:"Reconstruction",catalog:"Catalog",uncertainty:"Distance uncertainty",dataStatus:"Data status",catalogObservation:"Catalog observation",observationReconstruction:"Observation-based reconstruction",representative:"Representative visualization",notice:"Observation-based reconstruction — not an external photograph of the Milky Way. Marker sizes are visually enhanced and are not physical galaxy-diameter scale.",reduced:"Reduced mode",retry:"Retry",returnNearby:"Return to Nearby Stars",phase4:"Cosmic Web / Observable Universe — Available in Phase 4",loadingMilky:"Loading Reid 2019 HMSFR catalog…",loadingLocal:"Loading Local Group catalog…",noResult:"No deployed catalog result found",primary:"Primary name",aliases:"Aliases",objectType:"Object type",sourceId:"Source ID",distance:"Distance",raDec:"RA / Dec",spiralArm:"Spiral arm",parallax:"Parallax",visualizationStatus:"Visualization status",coordinateFrame:"Coordinate frame",sourceCatalog:"Source catalog",visualNotice:"Visualization notice"},
    "zh-TW":{phase3:"Phase 3",milkyWay:"銀河系",galacticCenter:"銀河中心",sagittarius:"人馬座 A*",galacticDisk:"銀河盤",galacticBar:"銀河棒",spiralArms:"旋臂",magellanic:"麥哲倫系統",localGroup:"本星系群",search:"搜尋",searchLabel:"Phase 3 星表搜尋",labels:"標籤",reconstruction:"觀測重建",catalog:"觀測星表",uncertainty:"距離不確定性",dataStatus:"資料狀態",catalogObservation:"星表觀測",observationReconstruction:"基於觀測的重建",representative:"代表性視覺化",notice:"基於觀測的重建，並非從銀河系外部拍攝的照片。標記尺寸經視覺增強，不代表星系實體直徑比例。",reduced:"精簡模式",retry:"重試",returnNearby:"返回鄰近恆星",phase4:"宇宙網／可觀測宇宙 — Phase 4 開放",loadingMilky:"正在載入 Reid 2019 HMSFR 星表…",loadingLocal:"正在載入本星系群星表…",noResult:"本地部署星表中找不到結果",primary:"主要名稱",aliases:"別名",objectType:"物件類型",sourceId:"來源 ID",distance:"距離",raDec:"赤經／赤緯",spiralArm:"旋臂",parallax:"視差",visualizationStatus:"視覺化狀態",coordinateFrame:"座標框架",sourceCatalog:"來源星表",visualNotice:"視覺化說明"},
    ja:{phase3:"Phase 3",milkyWay:"天の川銀河",galacticCenter:"銀河中心",sagittarius:"いて座A*",galacticDisk:"銀河円盤",galacticBar:"銀河バー",spiralArms:"渦状腕",magellanic:"マゼラン系",localGroup:"局所銀河群",search:"検索",searchLabel:"Phase 3 カタログ検索",labels:"ラベル",reconstruction:"観測再構成",catalog:"観測カタログ",uncertainty:"距離の不確かさ",dataStatus:"データ状態",catalogObservation:"カタログ観測",observationReconstruction:"観測に基づく再構成",representative:"代表可視化",notice:"観測に基づく再構成であり、天の川銀河を外部から撮影した写真ではありません。マーカーは視認性のため拡大され、銀河の実直径スケールではありません。",reduced:"縮小モード",retry:"再試行",returnNearby:"近傍恒星へ戻る",phase4:"コズミックウェブ／観測可能な宇宙 — Phase 4で利用可能",loadingMilky:"Reid 2019 HMSFRカタログを読み込み中…",loadingLocal:"局所銀河群カタログを読み込み中…",noResult:"配備済みカタログに結果がありません",primary:"主名称",aliases:"別名",objectType:"天体種別",sourceId:"ソースID",distance:"距離",raDec:"赤経／赤緯",spiralArm:"渦状腕",parallax:"年周視差",visualizationStatus:"可視化状態",coordinateFrame:"座標系",sourceCatalog:"出典カタログ",visualNotice:"可視化注記"},
    ko:{phase3:"Phase 3",milkyWay:"은하수",galacticCenter:"은하 중심",sagittarius:"궁수자리 A*",galacticDisk:"은하 원반",galacticBar:"은하 막대",spiralArms:"나선팔",magellanic:"마젤란계",localGroup:"국부 은하군",search:"검색",searchLabel:"Phase 3 카탈로그 검색",labels:"레이블",reconstruction:"관측 기반 재구성",catalog:"관측 카탈로그",uncertainty:"거리 불확도",dataStatus:"데이터 상태",catalogObservation:"카탈로그 관측",observationReconstruction:"관측 기반 재구성",representative:"대표 시각화",notice:"관측 기반 재구성이며 은하수 외부에서 촬영한 사진이 아닙니다. 마커는 시인성을 위해 확대되었으며 실제 은하 직경 축척이 아닙니다.",reduced:"축소 모드",retry:"다시 시도",returnNearby:"인접 항성으로 돌아가기",phase4:"우주 거미줄／관측 가능한 우주 — Phase 4에서 제공",loadingMilky:"Reid 2019 HMSFR 카탈로그 로드 중…",loadingLocal:"국부 은하군 카탈로그 로드 중…",noResult:"배포된 카탈로그에 결과가 없습니다",primary:"기본 이름",aliases:"별칭",objectType:"천체 유형",sourceId:"소스 ID",distance:"거리",raDec:"적경／적위",spiralArm:"나선팔",parallax:"시차",visualizationStatus:"시각화 상태",coordinateFrame:"좌표계",sourceCatalog:"출처 카탈로그",visualNotice:"시각화 안내"}
  });
  const SOLAR_COPY=Object.freeze({
    en:{displayEpoch:"DISPLAY EPOCH",source:"SOURCE",catalogEphemeris:"CATALOG / EPHEMERIS",referenceFrame:"REFERENCE FRAME",positionMode:"POSITION MODE",lastDataUpdate:"LAST DATA UPDATE",qualityStatus:"UNCERTAINTY / QUALITY STATUS"},
    "zh-TW":{displayEpoch:"顯示曆元",source:"來源",catalogEphemeris:"星表／星曆",referenceFrame:"參考框架",positionMode:"位置模式",lastDataUpdate:"最後資料更新",qualityStatus:"不確定性／品質狀態"},
    ja:{displayEpoch:"表示元期",source:"ソース",catalogEphemeris:"カタログ／暦",referenceFrame:"基準座標系",positionMode:"位置モード",lastDataUpdate:"最終データ更新",qualityStatus:"不確かさ／品質状態"},
    ko:{displayEpoch:"표시 역기점",source:"출처",catalogEphemeris:"카탈로그／천체력",referenceFrame:"기준 좌표계",positionMode:"위치 모드",lastDataUpdate:"마지막 데이터 업데이트",qualityStatus:"불확도／품질 상태"}
  });
  const PLANETS = DS.PLANET_IDS;
  const solarTime = new SolarCore.SolarSystemTimeState(new Date());
  let viewer, host, overlay, viewport, sourceParent, sourceNext, dataSource, clickHandler, tickRemover, navigationAbort, pinchState, nearbyCatalog, nearbyLayer, milkyWayCatalog, milkyWayLayer, localGroupCatalog, localGroupLayer, mainBeltLayer;
  let active=false, paused=false, speed=1, lastTick=0, mode="exhibition", selected="sun", focusParent=null, follow=false, solarSolution=null;
  let scaleContext="solar",nearbyActive=false,nearbyTier="10pc",nearbySelected=null,phase3Selected=null,smallBodySelected=null,loadToken=0,lastSatelliteOrbitDay=null,lastPlanetOrbitKey=null,lastSmallBodyDay=null;
  let saved={};
  const orbitCache = new Map();
  const ORBIT_SAMPLE_DENSITY=180;

  const l=()=>COPY[global.PCSI18n?.getLanguage?.()]||COPY.en;
  const nl=()=>NEAR_COPY[global.PCSI18n?.getLanguage?.()]||NEAR_COPY.en;
  const p3=()=>PHASE3_COPY[global.PCSI18n?.getLanguage?.()]||PHASE3_COPY.en;
  const sl=()=>SOLAR_COPY[global.PCSI18n?.getLanguage?.()]||SOLAR_COPY.en;
  const objectCardCopy=()=>ObjectCard.COPY[global.PCSI18n?.getLanguage?.()]||ObjectCard.COPY.en;
  const q=(selector)=>overlay?.querySelector(selector);
  const body=(id)=>DS.BODY_REGISTRY[id];
  const exhibitionDistance=(distanceAu)=> distanceAu===0?0:(250000+Math.log10(1+distanceAu)*1550000);
  const positionFor=(id,state)=>{
    if (!state) return null;
    const factor=mode==="scientific"?Eph.AU_KM:1;
    const distance=state.heliocentricDistanceAu ?? Math.hypot(...state.positionAu);
    const mapped=mode==="scientific"?distance*factor:exhibitionDistance(distance);
    const norm=Math.max(distance,1e-12);
    return new Cesium.Cartesian3(...state.positionAu.map((value)=>value/norm*mapped));
  };
  const radiusFor=(entry)=> mode==="scientific"?entry.radiusKm:Math.max(8000,Math.log10(entry.radiusKm+10)*3700);
  const cartesianArray=(value)=>[value.x,value.y,value.z];
  const displayEpoch=()=>solarTime.displayEpoch;
  function nearbySelectedDebug(){if(!nearbySelected)return null;const pair=nearbyLayer?.pointRecords?.find(([,record])=>String(record.id||record.source_id)===String(nearbySelected.id||nearbySelected.source_id)),position=pair?.[0]?.position;return {id:String(nearbySelected.id||nearbySelected.source_id||""),sourceCatalog:nearbySelected.sourceCatalog,referenceEpoch:nearbySelected.referenceEpoch,radialVelocityAvailable:nearbySelected.radialVelocityAvailable,position:position?{x:position.x,y:position.y,z:position.z}:null,metadata:Nearby.catalogMetadata(nearbySelected)};}

  function selectedScenePosition(){
    if(scaleContext==="solar"){const entity=dataSource?.entities?.getById(smallBodySelected?`deep-space-small-${smallBodySelected.spkid}`:`deep-space-${selected}`),entityPosition=entity?.position?.getValue(Cesium.JulianDate.now());if(entityPosition)return entityPosition;if(smallBodySelected&&mainBeltLayer){const index=mainBeltLayer.records.findIndex(item=>item.spkid===smallBodySelected.spkid);return index>=0?mainBeltLayer.points[index]?.position||null:null;}return null;}
    if(scaleContext==="nearby"&&nearbySelected?.cartesianPc){const value=Nearby.scenePosition(nearbySelected,mode);return new Cesium.Cartesian3(...value);}
    if((scaleContext==="milky-way"||scaleContext==="local-group")&&phase3Selected){const xyz=phase3Selected.galactocentricCartesianKpc||phase3Selected.heliocentricGalacticCartesianKpc;if(xyz){const value=Coordinates.scenePosition(xyz,mode,scaleContext==="milky-way"?"milky-way":"local-group");return new Cesium.Cartesian3(...value);}}
    return null;
  }
  function screenCenterAnchor(){const distance=Math.max(viewer.camera.frustum.near*20,Cesium.Cartesian3.magnitude(viewer.camera.positionWC)*.2,1000);return Cesium.Cartesian3.add(viewer.camera.positionWC,Cesium.Cartesian3.multiplyByScalar(viewer.camera.directionWC,distance,new Cesium.Cartesian3()),new Cesium.Cartesian3());}
  function navigationAnchor(screenPosition){
    const picked=viewer.scene.pick(screenPosition),orbitId=picked?.id?.properties?.orbitBodyId?.getValue?.()||picked?.id?.properties?.orbitBodyId;
    if(!orbitId&&picked&&viewer.scene.pickPositionSupported){const position=viewer.scene.pickPosition(screenPosition);if(position&&[position.x,position.y,position.z].every(Number.isFinite)){const bodyId=picked?.id?.properties?.deepSpaceBodyId?.getValue?.(),entry=body(bodyId);return {position,minDistance:entry?Math.max(radiusFor(entry)*1.08,viewer.camera.frustum.near*4):viewer.camera.frustum.near*4,source:"picked-scene"};}}
    const selectedPosition=selectedScenePosition();if(selectedPosition){const selectedRadius=smallBodySelected?Math.max((smallBodySelected.diameterKm||2000)/2,8000):radiusFor(body(selected));return {position:selectedPosition,minDistance:scaleContext==="solar"?Math.max(selectedRadius*1.08,viewer.camera.frustum.near*4):viewer.camera.frustum.near*4,source:orbitId?"selected-object-after-orbit-rejection":"selected-object"};}
    return {position:screenCenterAnchor(),minDistance:viewer.camera.frustum.near*4,source:"screen-center"};
  }
  function applyAnchoredZoom(screenPosition,scale,inputType){
    if(!active)return false;const anchor=navigationAnchor(screenPosition),result=PointerNavigation.anchoredPosition(cartesianArray(viewer.camera.positionWC),cartesianArray(anchor.position),scale,anchor.minDistance,viewer.scene.screenSpaceCameraController.maximumZoomDistance);if(!result)return false;
    viewer.camera.setView({destination:new Cesium.Cartesian3(...result.position),orientation:{direction:viewer.camera.directionWC,up:viewer.camera.upWC}});viewer.scene.requestRender();saved.lastPointerZoom={inputType,anchorSource:anchor.source,scale:result.scale};return true;
  }
  function setupPointerNavigation(){
    const canvas=viewer.scene.canvas;navigationAbort=new AbortController();const options={signal:navigationAbort.signal,passive:false};
    canvas.addEventListener("wheel",event=>{const rect=canvas.getBoundingClientRect(),position=new Cesium.Cartesian2(event.clientX-rect.left,event.clientY-rect.top);if(applyAnchoredZoom(position,PointerNavigation.wheelScale(event.deltaY),event.ctrlKey?"trackpad-pinch":"mouse-wheel"))event.preventDefault();},options);
    canvas.addEventListener("touchstart",event=>{if(event.touches.length===2)pinchState=PointerNavigation.touchMetrics(event.touches,canvas.getBoundingClientRect());},{signal:navigationAbort.signal,passive:true});
    canvas.addEventListener("touchmove",event=>{if(event.touches.length!==2||!pinchState)return;const current=PointerNavigation.touchMetrics(event.touches,canvas.getBoundingClientRect());if(current&&applyAnchoredZoom(new Cesium.Cartesian2(...current.center),PointerNavigation.pinchScale(pinchState.distance,current.distance),"mobile-pinch")){event.preventDefault();pinchState=current;}},options);
    canvas.addEventListener("touchend",()=>{pinchState=null;},{signal:navigationAbort.signal,passive:true});canvas.addEventListener("touchcancel",()=>{pinchState=null;},{signal:navigationAbort.signal,passive:true});
    viewer.scene.screenSpaceCameraController.enableZoom=false;
  }
  function disposePointerNavigation(){navigationAbort?.abort();navigationAbort=null;pinchState=null;viewer.scene.screenSpaceCameraController.enableZoom=saved.zoomEnabled;}

  function template(){
    return `<section class="deep-space-shell" role="dialog" aria-modal="true" aria-labelledby="deep-space-title">
      <header class="deep-space-header"><div><strong id="deep-space-title"></strong><span data-ds-level>Level 2 — Solar System</span></div><div><time data-ds-epoch></time><button data-ds-collapse type="button"></button><button data-ds-close type="button" class="deep-space-close"></button></div></header>
      <div class="deep-space-viewport" data-ds-viewport></div>
      <aside class="deep-space-controls" data-ds-controls><p class="deep-space-connectivity" data-ds-connectivity role="status"></p>
        <section><h2 data-copy="scale"></h2><div class="deep-space-row"><button data-mode="exhibition"></button><button data-mode="scientific"></button></div><p data-ds-scale-notice></p></section>
        <section data-ds-phase1-time><h2 data-copy="time"></h2><div class="deep-space-row"><button data-ds-play></button><select data-ds-speed aria-label="Playback speed">${Object.keys(SPEEDS).map((name)=>`<option>${name}</option>`).join("")}</select><button data-ds-step="-1">−1 d</button><button data-ds-step="1">+1 d</button><button data-ds-now></button></div><dl class="deep-space-solar-metadata">${["displayEpoch","source","catalogEphemeris","referenceFrame","positionMode","lastDataUpdate","qualityStatus"].map(key=>`<div><dt data-solar-label="${key}"></dt><dd data-solar-field="${key}"></dd></div>`).join("")}</dl></section><p data-ds-status></p>
        <section><h2 data-copy="objects"></h2><div class="deep-space-object-list">${["sun",...PLANETS,...DS.SATELLITE_IDS].map((id)=>`<button data-body="${id}">${body(id).name}</button>`).join("")}${SmallBodies.dataset.dwarfPlanets.map(record=>`<button data-small-body="${record.spkid}">${record.name}</button>`).join("")}</div><button data-ds-nearby type="button"></button><div data-ds-tiers class="deep-space-row" hidden>${Nearby.CONFIG.map(c=>`<button data-tier="${c.id}">${c.radiusPc} pc</button>`).join("")}</div><div class="deep-space-row"><button data-ds-milky-way type="button" data-p3="milkyWay"></button><button data-ds-galactic-center type="button" data-p3="galacticCenter"></button><button data-ds-magellanic type="button" data-p3="magellanic"></button><button data-ds-local-group type="button" data-p3="localGroup"></button></div><p data-ds-phase2></p><p data-ds-phase3></p><p data-p3="phase4"></p></section>
        <section data-ds-near-controls hidden><h2 data-near="search"></h2><form data-ds-search><input data-ds-search-input type="search" autocomplete="off"><button type="submit" data-near="search"></button></form><p data-ds-search-status aria-live="polite"></p><div class="deep-space-row"><label><input data-ds-quality type="checkbox"> <span data-near="quality"></span></label><label><input data-ds-motion type="checkbox"> <span data-near="motion"></span></label><label><input data-ds-guides type="checkbox" checked> <span data-near="guides"></span></label></div><label class="deep-space-year"><span data-near="analysisYear"></span><input data-ds-analysis-year type="number" min="1916" max="2116" value="2016"></label><p data-near="propagation"></p><p data-ds-motion-warning hidden></p><div data-ds-quality-legend class="deep-space-quality-legend" hidden><strong data-near="legend"></strong><span data-quality="high-confidence astrometry">high-confidence</span><span data-quality="catalog astrometry">catalog</span><span data-quality="limited astrometry">limited</span><span data-quality="incomplete 6D state">incomplete 6D</span><span data-quality="supplemental Hipparcos">supplemental</span></div><p data-near="marker"></p></section>
        <section data-ds-phase3-controls hidden><h2 data-p3="phase3"></h2><form data-ds-phase3-search><input data-ds-phase3-search-input type="search" autocomplete="off"><button type="submit" data-p3="search"></button></form><p data-ds-phase3-search-status aria-live="polite"></p><div class="deep-space-row"><label><input data-ds-phase3-labels type="checkbox" checked> <span data-p3="labels"></span></label><label><input data-ds-reconstruction type="checkbox" checked> <span data-p3="reconstruction"></span></label><label><input data-ds-catalog type="checkbox" checked> <span data-p3="catalog"></span></label><label><input data-ds-uncertainty type="checkbox"> <span data-p3="uncertainty"></span></label></div><div class="deep-space-quality-legend"><strong data-p3="dataStatus"></strong><span data-p3="catalogObservation"></span><span data-p3="observationReconstruction"></span><span data-p3="representative"></span></div><p data-p3="notice"></p><button type="button" data-ds-return-nearby data-p3="returnNearby"></button></section>
        <section><h2 data-copy="orbits"></h2><div class="deep-space-row"><label><input data-ds-orbits type="checkbox" checked> <span data-copy="orbits"></span></label><label><input data-ds-labels type="checkbox" checked> <span data-copy="labels"></span></label><label><input data-ds-dwarfs type="checkbox" checked> <span data-copy="dwarfPlanets"></span></label><label><input data-ds-main-belt type="checkbox" checked> <span data-copy="mainBelt"></span></label></div></section>
        <section data-object-card hidden aria-live="polite"><header class="deep-space-card-header"><h2 data-object-card-title></h2><div><button data-object-card-focus type="button"></button><button data-object-card-close type="button"></button></div></header><div data-ds-info class="deep-space-info"></div></section>
        <section class="deep-space-actions"><button data-ds-reset></button><button data-ds-solar></button><button data-ds-earth></button><button data-ds-follow></button><button data-ds-top></button><button data-ds-inclined></button></section>
      </aside><div class="deep-space-error" data-ds-error hidden role="alert"><p data-ds-error-message></p><div class="deep-space-row"><button data-ds-retry data-near="retry"></button><button data-ds-reduced data-near="reduced"></button><button data-ds-error-solar data-near="returnSolar"></button><button data-ds-error-close data-near="close"></button></div></div>
    </section>`;
  }
  function renderScaleTitle(){
    if(scaleContext==="nearby")q("[data-ds-level]").textContent=`Level ${4+Nearby.CONFIG.findIndex(c=>c.id===nearbyTier)} — ${nl().neighborhood} ${nearbyTier.replace("pc"," pc")}`;
    else if(scaleContext==="milky-way")q("[data-ds-level]").textContent=`Level 8 — ${p3().milkyWay} / ${p3().galacticCenter}`;
    else if(scaleContext==="local-group")q("[data-ds-level]").textContent=`Level 9 — ${p3().localGroup}`;
  }
  function translate(){
    if(!overlay)return; const c=l(); q("#deep-space-title").textContent=c.title; q("[data-ds-close]").textContent=c.close;
    overlay.querySelectorAll("[data-copy]").forEach((el)=>el.textContent=c[el.dataset.copy]);
    q('[data-mode="exhibition"]').textContent=c.exhibition;q('[data-mode="scientific"]').textContent=c.scientific;q("[data-ds-play]").textContent=paused?c.play:c.pause;q("[data-ds-now]").textContent=c.now;q("[data-ds-phase2]").textContent=nearbyActive?`${nl().frame}: ${nearbySelected?.coordinateFrame||"GCNS heliocentric Galactic Cartesian"}`:c.phase2;q("[data-ds-nearby]").textContent=nl().nearby;q("[data-ds-phase3]").textContent=nl().phase3;overlay.querySelectorAll("[data-near]").forEach(el=>el.textContent=nl()[el.dataset.near]);
    overlay.querySelectorAll("[data-ds-later]").forEach((el)=>el.textContent=c.later);
    overlay.querySelectorAll("[data-p3]").forEach((el)=>{const text=p3()[el.dataset.p3];el.textContent=text;if(el.matches("button")){el.title=text;el.setAttribute("aria-label",text);}});
    overlay.querySelectorAll("[data-solar-label]").forEach(el=>el.textContent=sl()[el.dataset.solarLabel]);
    const phase3Search=q("[data-ds-phase3-search-input]");phase3Search.placeholder=p3().searchLabel;phase3Search.setAttribute("aria-label",p3().searchLabel);
    renderScaleTitle();
    [["[data-ds-reset]","reset"],["[data-ds-solar]","solar"],["[data-ds-earth]","earth"],["[data-ds-follow]","follow"],["[data-ds-top]","top"],["[data-ds-inclined]","inclined"]].forEach(([s,k])=>q(s).textContent=c[k]);
    q("[data-ds-collapse]").textContent=q("[data-ds-controls]").classList.contains("is-collapsed")?c.expand:c.collapse;
    const connectivity=CONNECTIVITY[global.PCSI18n?.getLanguage?.()]||CONNECTIVITY.en;q("[data-ds-connectivity]").textContent=navigator.onLine?connectivity.online:connectivity.offline;q("[data-ds-connectivity]").classList.toggle("is-offline",!navigator.onLine);
    q("[data-ds-scale-notice]").textContent=mode==="scientific"?c.noticeSci:c.noticeEx;if(!q("[data-object-card]").hidden){if(scaleContext==="nearby"&&nearbySelected)renderNearbyInfo(nearbySelected);else if((scaleContext==="milky-way"||scaleContext==="local-group")&&phase3Selected){if(String(phase3Selected.id).startsWith("milky-way:spiral-arm:"))showObjectCard(phase3Selected);else selectPhase3(phase3Selected);}else if(scaleContext==="solar")renderInfo(false);}
  }
  function setupOverlay(){
    overlay=document.createElement("div");overlay.className="deep-space-overlay";overlay.hidden=true;overlay.innerHTML=template();document.body.append(overlay);viewport=q("[data-ds-viewport]");translate();
    q("[data-ds-close]").addEventListener("click",close);q("[data-ds-collapse]").addEventListener("click",()=>{q("[data-ds-controls]").classList.toggle("is-collapsed");translate();});
    overlay.querySelectorAll("[data-mode]").forEach((b)=>b.addEventListener("click",()=>{mode=b.dataset.mode;if(scaleContext==="nearby")enterNearby(nearbyTier);else if(scaleContext==="milky-way")enterMilkyWay();else if(scaleContext==="local-group")enterLocalGroup();else renderAll();}));
    overlay.querySelectorAll("[data-body]").forEach((b)=>b.addEventListener("click",()=>selectBody(b.dataset.body)));
    overlay.querySelectorAll("[data-small-body]").forEach((b)=>b.addEventListener("click",()=>selectSmallBody(b.dataset.smallBody)));
    q("[data-ds-nearby]").addEventListener("click",()=>enterNearby("10pc"));q("[data-ds-return-nearby]").addEventListener("click",()=>enterNearby("10pc"));overlay.querySelectorAll("[data-tier]").forEach(b=>b.addEventListener("click",()=>enterNearby(b.dataset.tier)));q("[data-ds-milky-way]").addEventListener("click",enterMilkyWay);q("[data-ds-galactic-center]").addEventListener("click",async()=>{await enterMilkyWay();selectPhase3(MilkyWay.MilkyWayLayer.SGR_A);});q("[data-ds-magellanic]").addEventListener("click",async()=>{await enterLocalGroup();searchPhase3("LMC");});q("[data-ds-local-group]").addEventListener("click",()=>enterLocalGroup());q("[data-ds-search]").addEventListener("submit",event=>{event.preventDefault();searchNearby(q("[data-ds-search-input]").value);});q("[data-ds-phase3-search]").addEventListener("submit",event=>{event.preventDefault();searchPhase3(q("[data-ds-phase3-search-input]").value);});q("[data-ds-labels]").addEventListener("change",()=>nearbyLayer?.setLabels(q("[data-ds-labels]").checked));q("[data-ds-quality]").addEventListener("change",event=>{nearbyLayer?.setQuality(event.target.checked);q("[data-ds-quality-legend]").hidden=!event.target.checked;});q("[data-ds-motion]").addEventListener("change",event=>nearbyLayer?.setMotion(event.target.checked));q("[data-ds-guides]").addEventListener("change",event=>nearbyLayer?.setGuides(event.target.checked));q("[data-ds-analysis-year]").addEventListener("input",updateMotionWindow);q("[data-ds-phase3-labels]").addEventListener("change",event=>{milkyWayLayer?.setLabels(event.target.checked);localGroupLayer?.setLabels(event.target.checked);});q("[data-ds-reconstruction]").addEventListener("change",event=>milkyWayLayer?.setReconstruction(event.target.checked));q("[data-ds-catalog]").addEventListener("change",event=>localGroupLayer?.setCatalog(event.target.checked));q("[data-ds-uncertainty]").addEventListener("change",event=>localGroupLayer?.setUncertainty(event.target.checked));
    q("[data-ds-play]").addEventListener("click",()=>{paused=!paused;translate();});q("[data-ds-speed]").addEventListener("change",(e)=>{speed=SPEEDS[e.target.value];});
    overlay.querySelectorAll("[data-ds-step]").forEach((b)=>b.addEventListener("click",()=>{solarTime.advance(Number(b.dataset.dsStep)*SolarCore.DAY_MS,"step");updatePositions();}));
    q("[data-ds-now]").addEventListener("click",()=>{solarTime.set(new Date(),"reset-now");updatePositions();});q("[data-ds-reset]").addEventListener("click",resetView);q("[data-ds-solar]").addEventListener("click",returnSolar);q("[data-ds-earth]").addEventListener("click",()=>{close();document.querySelector('[data-solar-target="earth"]')?.click();});
    q("[data-ds-follow]").addEventListener("click",()=>{follow=!follow;q("[data-ds-follow]").classList.toggle("is-active",follow);});q("[data-ds-top]").addEventListener("click",()=>setCamera("top"));q("[data-ds-inclined]").addEventListener("click",()=>setCamera("inclined"));
    q("[data-object-card-focus]").addEventListener("click",focusSelectedObject);q("[data-object-card-close]").addEventListener("click",closeObjectCard);
    q("[data-ds-orbits]").addEventListener("change",renderAll);q("[data-ds-dwarfs]").addEventListener("change",renderAll);q("[data-ds-main-belt]").addEventListener("change",renderAll);q("[data-ds-labels]").addEventListener("change",()=>dataSource.entities.values.forEach((e)=>{if(e.label)e.label.show=q("[data-ds-labels]").checked;}));
    q("[data-ds-retry]").addEventListener("click",()=>scaleContext==="milky-way"?enterMilkyWay():scaleContext==="local-group"?enterLocalGroup():enterNearby(nearbyTier));q("[data-ds-reduced]").addEventListener("click",()=>scaleContext==="milky-way"?enterMilkyWay({reduced:true}):scaleContext==="local-group"?enterLocalGroup({reduced:true}):enterNearby(nearbyTier,{reduced:true}));q("[data-ds-error-solar]").addEventListener("click",returnSolar);q("[data-ds-error-close]").addEventListener("click",close);overlay.addEventListener("keydown",trapFocus);global.addEventListener("pcs:languagechange",translate);global.addEventListener("online",translate);global.addEventListener("offline",translate);
  }
  function orbitPoints(id){const entry=body(id),epoch=displayEpoch(),centerDay=epoch.toISOString().slice(0,10),key=`${mode}:${solarSolution?.id}:${id}:${centerDay}:${ORBIT_SAMPLE_DENSITY}`;if(orbitCache.has(key))return orbitCache.get(key);const points=Eph.sampleOrbit(id,epoch,{solution:solarSolution,sampleDensity:ORBIT_SAMPLE_DENSITY,pastDays:Math.abs(entry.orbitalPeriodDays)/2,futureDays:Math.abs(entry.orbitalPeriodDays)/2}).map(state=>positionFor(id,state)).filter(Boolean);orbitCache.set(key,points);return points;}
  function satelliteCompression(entry){return mode==="scientific"?1:Math.max(18,150000/Math.max(entry.meanOrbitalRadiusKm,1));}
  function solidBodyLod(entry){const displayRadius=radiusFor(entry),transitionDistance=Math.max(displayRadius*180,120000),displayRadiusScale=displayRadius/entry.radiusKm;return Object.freeze({physicalRadiusKm:entry.radiusKm,displayRadius,displayRadiusScale,transitionDistance,overlapStart:transitionDistance*.82,adjusted:Math.abs(displayRadiusScale-1)>1e-9,notice:Math.abs(displayRadiusScale-1)<=1e-9?"Physical radius":displayRadiusScale>1?"Display radius visually enlarged":"Display radius visually compressed"});}
  function satelliteOrbitPoints(id,parentPosition){const entry=body(id),compression=satelliteCompression(entry);return Eph.sampleOrbit(id,displayEpoch(),{sampleDensity:120,pastDays:Math.abs(entry.orbitalPeriodDays)/2,futureDays:Math.abs(entry.orbitalPeriodDays)/2}).map(state=>Cesium.Cartesian3.add(parentPosition,new Cesium.Cartesian3(...state.positionAu.map(value=>value*Eph.AU_KM*compression)),new Cesium.Cartesian3()));}
  function addOrbit(entry,parentPosition){const positions=parentPosition?satelliteOrbitPoints(entry.id,parentPosition):orbitPoints(entry.id);if(positions.length<2)return null;return dataSource.entities.add({id:`deep-space-orbit-${entry.id}`,name:`${entry.name} orbit`,polyline:{positions,width:entry.id===selected?3:1,material:Cesium.Color.fromCssColorString(entry.color).withAlpha(entry.id===selected?.82:.42)},properties:{orbitBodyId:entry.id,parentBodyId:entry.parentBodyId,solutionId:solarSolution?.id,positionMode:solarSolution?.positionMode,precisionStatus:entry.orbit.precisionStatus,dataSource:solarSolution?.source||entry.orbit.dataSource,epoch:solarSolution?.displayEpoch||entry.orbit.epoch,coordinateFrame:solarSolution?.referenceFrame||entry.orbit.coordinateFrame,validTimeRange:JSON.stringify(solarSolution?.validity||entry.orbit.validTimeRange),fallbackStatus:solarSolution?.qualityStatus||entry.orbit.fallbackStatus}});}
  function addEntity(entry,state,parentPosition){
    let position=parentPosition||positionFor(entry.id,state);if(!position)return;
    if(parentPosition){const rel=state||Eph.getSatelliteRelativeState(entry.id,displayEpoch());if(!rel)return;const compression=satelliteCompression(entry);position=Cesium.Cartesian3.add(parentPosition,new Cesium.Cartesian3(...rel.positionAu.map(v=>v*Eph.AU_KM*compression)),new Cesium.Cartesian3());state=rel;}
    const lod=solidBodyLod(entry),color=Cesium.Color.fromCssColorString(entry.color);
    const entity=dataSource.entities.add({id:`deep-space-${entry.id}`,name:entry.name,position,point:{pixelSize:9,color,outlineColor:Cesium.Color.BLACK.withAlpha(.65),outlineWidth:1,scaleByDistance:new Cesium.NearFarScalar(lod.transitionDistance*4,1.45,lod.transitionDistance*60,.72),distanceDisplayCondition:new Cesium.DistanceDisplayCondition(lod.overlapStart,Number.MAX_VALUE)},ellipsoid:{radii:new Cesium.Cartesian3(lod.displayRadius,lod.displayRadius,lod.displayRadius),material:color,outline:true,outlineColor:Cesium.Color.WHITE.withAlpha(.28),distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,lod.transitionDistance)},label:{text:entry.name,font:"13px system-ui",fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,pixelOffset:new Cesium.Cartesian2(0,-18),show:q("[data-ds-labels]").checked},properties:{deepSpaceBodyId:entry.id,physicalRadiusKm:lod.physicalRadiusKm,displayRadius:lod.displayRadius,displayRadiusScale:lod.displayRadiusScale,displayRadiusAdjusted:lod.adjusted,visualScaleNotice:lod.notice,lodContract:"point → scaled intermediate marker → overlapping solid sphere",solutionId:state?.solutionId,source:state?.source,displayEpoch:state?.epoch}});return entity;
  }
  function addDwarfEntity(record){const state=SmallBodies.stateAt(record,displayEpoch()),position=positionFor(record.spkid,state);if(!position)return null;const color=Cesium.Color.fromCssColorString({Ceres:"#b9aa92",Pluto:"#c8aa8d",Eris:"#c8d0d5",Haumea:"#d6cab8",Makemake:"#ba8467"}[record.name]||"#b9aa92"),radius=record.diameterKm==null?null:record.diameterKm/2,displayRadius=radius==null?null:(mode==="scientific"?radius:Math.max(6500,Math.log10(radius+10)*3300));return dataSource.entities.add({id:`deep-space-small-${record.spkid}`,name:record.name,position,point:{pixelSize:10,color,outlineColor:Cesium.Color.BLACK,outlineWidth:1},ellipsoid:displayRadius==null?undefined:{radii:new Cesium.Cartesian3(displayRadius,displayRadius,displayRadius),material:color,distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,Math.max(displayRadius*180,120000))},label:{text:record.name,font:"13px system-ui",fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,pixelOffset:new Cesium.Cartesian2(0,-18),show:q("[data-ds-labels]").checked},properties:{smallBodySpkid:record.spkid,objectType:"dwarf planet",physicalDiameterKm:record.diameterKm,displayRadius,visualScaleNotice:record.diameterKm==null?"Point marker; physical diameter unavailable in deployed SBDB record":mode==="scientific"?"Physical radius":"Display radius visually adjusted",source:state.source,solutionEpochJdTdb:state.solutionEpochJdTdb,displayEpoch:state.epoch,positionMode:state.positionMode}});}
  function renderAll(){
    if(!dataSource||scaleContext!=="solar")return;dataSource.entities.removeAll();const epoch=displayEpoch(),showOrbits=q("[data-ds-orbits]").checked;solarSolution=Eph.createDisplaySolution(epoch,PLANETS);const orbitKey=`${mode}:${solarSolution.id}:${epoch.toISOString().slice(0,10)}`;if(orbitKey!==lastPlanetOrbitKey)orbitCache.clear();lastPlanetOrbitKey=orbitKey;
    addEntity(body("sun"),Eph.getStateFromSolution(solarSolution,"sun",epoch));
    PLANETS.forEach((id)=>{const entry=body(id),state=Eph.getStateFromSolution(solarSolution,id,epoch),entity=addEntity(entry,state);if(showOrbits)addOrbit(entry);if(focusParent===id&&entity){const parentPosition=entity.position.getValue(Cesium.JulianDate.now());DS.SATELLITE_IDS.filter(s=>body(s).parentBodyId===id).forEach(s=>{const satellite=body(s),satelliteState=Eph.getSatelliteRelativeState(s,epoch);const satelliteEntity=addEntity(satellite,satelliteState,parentPosition);if(showOrbits&&satelliteEntity)addOrbit(satellite,parentPosition);});}});
    if(q("[data-ds-dwarfs]").checked)SmallBodies.dataset.dwarfPlanets.forEach(addDwarfEntity);
    if(q("[data-ds-main-belt]").checked)mainBeltLayer.load(SmallBodies.dataset.mainBelt.records,epoch,mode);else mainBeltLayer.unload();lastSmallBodyDay=epoch.toISOString().slice(0,10);
    updatePositions();translate();viewer.scene.requestRender();
  }
  function updateSolarMetadata(){if(!solarSolution)return;const values={displayEpoch:`${solarSolution.displayEpoch.replace(".000Z","")} ${solarSolution.displayTimeScale}`,source:solarSolution.source,catalogEphemeris:solarSolution.catalogEphemeris,referenceFrame:solarSolution.referenceFrame,positionMode:solarSolution.positionMode,lastDataUpdate:solarSolution.lastDataUpdate,qualityStatus:`${solarSolution.qualityStatus}; ${solarSolution.uncertainty}`};for(const [key,value] of Object.entries(values)){const field=q(`[data-solar-field="${key}"]`);if(field)field.textContent=value;}q("[data-ds-epoch]").textContent=values.displayEpoch;q("[data-ds-status]").textContent=`${solarSolution.positionMode} · ${solarSolution.referenceFrame}`;}
  function updateNearbyEpochPresentation(){if(scaleContext!=="nearby")return;q("[data-ds-epoch]").textContent=`${objectCardCopy().displayEpoch}: ${displayEpoch().toISOString().replace(".000Z"," UTC")}`;if(nearbySelected&&!q("[data-object-card]").hidden)renderNearbyInfo(nearbySelected);}
  function updatePositions(){
    if(!active)return;if(scaleContext==="nearby"){updateNearbyEpochPresentation();return;}if(scaleContext!=="solar")return;const epoch=displayEpoch();solarSolution=Eph.createDisplaySolution(epoch,PLANETS);const orbitKey=`${mode}:${solarSolution.id}:${epoch.toISOString().slice(0,10)}`;if(orbitKey!==lastPlanetOrbitKey)return renderAll();PLANETS.forEach((id)=>{const entity=dataSource.entities.getById(`deep-space-${id}`),state=Eph.getStateFromSolution(solarSolution,id,epoch),position=positionFor(id,state);if(entity){entity.show=Boolean(position);if(position)entity.position=position;}});
    if(focusParent){const p=dataSource.entities.getById(`deep-space-${focusParent}`)?.position?.getValue(Cesium.JulianDate.now()),orbitDay=epoch.toISOString().slice(0,10),refreshOrbits=orbitDay!==lastSatelliteOrbitDay;DS.SATELLITE_IDS.filter(s=>body(s).parentBodyId===focusParent).forEach((id)=>{const entity=dataSource.entities.getById(`deep-space-${id}`),orbit=dataSource.entities.getById(`deep-space-orbit-${id}`),rel=Eph.getSatelliteRelativeState(id,epoch);if(entity&&p&&rel){const compression=satelliteCompression(body(id));entity.position=Cesium.Cartesian3.add(p,new Cesium.Cartesian3(...rel.positionAu.map(v=>v*Eph.AU_KM*compression)),new Cesium.Cartesian3());if(orbit&&refreshOrbits)orbit.polyline.positions=satelliteOrbitPoints(id,p);}});lastSatelliteOrbitDay=orbitDay;}
    SmallBodies.dataset.dwarfPlanets.forEach(record=>{const entity=dataSource.entities.getById(`deep-space-small-${record.spkid}`),state=SmallBodies.stateAt(record,epoch),position=positionFor(record.spkid,state);if(entity&&position)entity.position=position;});const smallBodyDay=epoch.toISOString().slice(0,10);if(mainBeltLayer&&smallBodyDay!==lastSmallBodyDay){mainBeltLayer.updateEpoch(epoch);lastSmallBodyDay=smallBodyDay;}
    updateSolarMetadata();renderInfo(false);viewer.scene.requestRender();
    if(follow){const e=dataSource.entities.getById(`deep-space-${selected}`);if(e)viewer.trackedEntity=e;}
  }
  const objectCardLanguage=()=>global.PCSI18n?.getLanguage?.()||"en";
  function showObjectCard(model){return ObjectCard.render(q("[data-object-card]"),model,objectCardLanguage());}
  function closeObjectCard(){const section=q("[data-object-card]");if(section){section.hidden=true;section.removeAttribute("data-object-id");}q("[data-ds-controls]")?.focus?.({preventScroll:true});}
  function renderInfo(force=true){if(!overlay||(!force&&q("[data-object-card]").hidden))return;if(smallBodySelected)return renderSmallBodyInfo(smallBodySelected);const epoch=displayEpoch(),entry=body(selected),state=entry.type==="natural-satellite"?Eph.getSatelliteRelativeState(selected,epoch):Eph.getStateFromSolution(solarSolution||Eph.createDisplaySolution(epoch,PLANETS),selected,epoch);showObjectCard(ObjectCard.solar(entry,state,objectCardLanguage()));}
  function renderSmallBodyInfo(record){smallBodySelected=record;selected=`sbdb:${record.spkid}`;return showObjectCard(ObjectCard.smallBody(record,SmallBodies.stateAt(record,displayEpoch()),objectCardLanguage()));}
  function renderNearbyInfo(record){if(!record)return;nearbySelected=record;nearbyLayer?.selection.select(record);showObjectCard(ObjectCard.nearby(record,objectCardLanguage(),{displayEpoch:displayEpoch()}));}
  function clearScaleLayers(){nearbyLayer?.unload();milkyWayLayer?.unload();localGroupLayer?.unload();mainBeltLayer?.unload();phase3Selected=null;smallBodySelected=null;closeObjectCard();viewer.trackedEntity=undefined;dataSource.entities.removeAll();}
  function setScaleControls(context){scaleContext=context;nearbyActive=context==="nearby";q("[data-ds-phase1-time]").hidden=context!=="solar";q("[data-ds-tiers]").hidden=context!=="nearby";q("[data-ds-near-controls]").hidden=context!=="nearby";q("[data-ds-phase3-controls]").hidden=!["milky-way","local-group"].includes(context);q("[data-ds-error]").hidden=true;}
  async function enterNearby(id,options={}){const token=++loadToken;setScaleControls("nearby");nearbyTier=id;nearbySelected=null;focusParent=null;clearScaleLayers();q("[data-ds-controls]").scrollTop=0;q("[data-ds-status]").textContent=nl().loading;q("[data-ds-level]").textContent=`Level ${4+Nearby.CONFIG.findIndex(c=>c.id===id)} — ${nl().neighborhood} ${id.replace("pc"," pc")}`;try{const lowMemory=Number(navigator.deviceMemory||8)<=2,loaded=options.reduced||lowMemory?await nearbyCatalog.loadReduced():await nearbyCatalog.load(id);if(token!==loadToken||scaleContext!=="nearby")return false;const config=Nearby.CONFIG.find(c=>c.id===id),mobile=global.matchMedia?.("(max-width: 700px)").matches,records=mobile?loaded.tier.records.slice(0,config.mobileMaxObjects):loaded.tier.records,renderConfig=Object.assign({},config,{renderMaxObjects:mobile?config.mobileMaxObjects:config.maxObjects});nearbyLayer.load(records,loaded.landmarks.records,renderConfig,mode);nearbyLayer.setLabels(q("[data-ds-labels]").checked);nearbyLayer.setQuality(q("[data-ds-quality]").checked);nearbyLayer.setMotion(q("[data-ds-motion]").checked);nearbyLayer.setGuides(q("[data-ds-guides]").checked);q("[data-ds-status]").textContent=`${nearbyLayer.records.length.toLocaleString()} objects · ${loaded.reduced?nl().reduced:config.dataSource} · ${config.release}`;updateNearbyEpochPresentation();setNearbyCamera(config.radiusPc);renderNearbyInfo(loaded.landmarks.records.find(x=>x.id==="sun"));translate();return true;}catch(error){if(token!==loadToken||error.name==="AbortError")return false;showScaleError(error);return false;}}
  function showScaleError(error){q("[data-ds-error]").hidden=false;q("[data-ds-error-message]").textContent=`Catalog loading failed: ${error.message}`;q("[data-ds-status]").textContent="Catalog loading failed";}
  async function enterMilkyWay(options={}){const token=++loadToken;setScaleControls("milky-way");clearScaleLayers();q("[data-ds-level]").textContent=`Level 8 — ${p3().milkyWay} / ${p3().galacticCenter}`;q("[data-ds-status]").textContent=p3().loadingMilky;try{const loaded=await milkyWayCatalog.load();if(token!==loadToken||scaleContext!=="milky-way")return false;const reduced=options.reduced||Number(navigator.deviceMemory||8)<=2,records=reduced?loaded.registry.records.filter((_,index)=>index%4===0):loaded.registry.records;milkyWayLayer.load(records,mode,{maxObjects:records.length});q("[data-ds-status]").textContent=`${records.length} HMSFR · Reid et al. 2019 · ${p3().observationReconstruction}${reduced?` · ${p3().reduced}`:""}`;q("[data-ds-epoch]").textContent="Galactocentric frame · R₀ 8.15 kpc";setPhase3Camera(20);selectPhase3(MilkyWay.MilkyWayLayer.SUN);translate();return true;}catch(error){if(token!==loadToken||error.name==="AbortError")return false;showScaleError(error);return false;}}
  async function enterLocalGroup(options={}){const token=++loadToken;setScaleControls("local-group");clearScaleLayers();q("[data-ds-level]").textContent=`Level 9 — ${p3().localGroup}`;q("[data-ds-status]").textContent=p3().loadingLocal;try{const reduced=options.reduced||Number(navigator.deviceMemory||8)<=2,loaded=await localGroupCatalog.load({reduced});if(token!==loadToken||scaleContext!=="local-group")return false;localGroupLayer.load(loaded.records,mode,{lod:reduced?"near":"far",showUncertainty:q("[data-ds-uncertainty]").checked});q("[data-ds-status]").textContent=`${loaded.records.length} ${p3().catalogObservation} · McConnachie 2012${reduced?` · ${p3().reduced}`:""}`;q("[data-ds-epoch]").textContent="Heliocentric Galactic Cartesian · J2000";setPhase3Camera(1500);selectPhase3(LocalGroup.MILKY_WAY);translate();return true;}catch(error){if(token!==loadToken||error.name==="AbortError")return false;showScaleError(error);return false;}}
  function selectPhase3(record){if(!record)return null;phase3Selected=record;showObjectCard(ObjectCard.phase3(record,scaleContext));return record;}
  function searchPhase3(term){const needle=String(term||"").trim().toLowerCase(),armCode=scaleContext==="milky-way"?Object.keys(MilkyWay.ARM_COLORS).find(code=>needle===code.toLowerCase()||needle===`${code.toLowerCase()} spiral arm`):null;if(armCode){phase3Selected=ObjectCard.reconstruction(armCode);showObjectCard(phase3Selected);q("[data-ds-phase3-search-status]").textContent=`${phase3Selected.canonicalName} · ${phase3Selected.dataStatus}`;return phase3Selected;}const match=scaleContext==="milky-way"?milkyWayCatalog.search(term):localGroupCatalog.search(term);if(!match){q("[data-ds-phase3-search-status]").textContent=p3().noResult;return null;}const distance=match.distanceKpc==null?nl().unavailable:`${match.distanceKpc} kpc`;q("[data-ds-phase3-search-status]").textContent=`${match.canonicalName} · ${distance} · ${match.objectType}`;selectPhase3(match);return match;}
  function setPhase3Camera(radiusKpc){const domain=scaleContext==="milky-way"?"milky-way":"local-group",height=Coordinates.sceneRadiusKpc(radiusKpc,mode,domain)*1.25;viewer.camera.flyTo({destination:new Cesium.Cartesian3(0,-height*.3,height),orientation:{heading:0,pitch:-Math.PI/3,roll:0},duration:.7});}
  function searchNearby(term){const needle=term.trim().toLowerCase();const records=[...(nearbyCatalog.landmarks?.records||[]),...(nearbyLayer?.records||[])],match=records.find(r=>String(r.source_id||"").toLowerCase()===needle||r.primaryName?.toLowerCase()===needle||r.primaryName?.toLowerCase().includes(needle)||r.aliases?.some(a=>a.toLowerCase()===needle||a.toLowerCase().includes(needle)));if(!match){q("[data-ds-search-status]").textContent=nl().notFound;return null;}q("[data-ds-search-status]").textContent=`${match.primaryName||match.source_id} · ${match.distancePc?.toFixed(3)??"?"} pc · ${match.objectType||"star"}`;renderNearbyInfo(match);return match;}
  function updateMotionWindow(){const year=Number(q("[data-ds-analysis-year]").value),reference=nearbySelected?.referenceEpoch||2016,clamped=Math.abs(year-reference)>100;q("[data-ds-motion-warning]").hidden=!clamped;q("[data-ds-motion-warning]").textContent=clamped?nl().windowWarning:"";}
  function setEpoch(value){try{solarTime.set(value,"api");updatePositions();return true;}catch(_error){return false;}}
  function selectBody(id){if(scaleContext!=="solar")returnSolar();smallBodySelected=null;selected=id;focusParent=body(id).type==="planet"?id:body(id).parentBodyId;lastSatelliteOrbitDay=null;q("[data-ds-level]").textContent=id==="earth"?"Level 0 — Earth System":id==="neptune"?"Level 3 — Outer Solar System Context":focusParent?"Level 1 — Planetary System":"Level 2 — Solar System";renderAll();renderInfo();}
  function selectSmallBody(spkid){if(scaleContext!=="solar")returnSolar();const record=[...SmallBodies.dataset.dwarfPlanets,...SmallBodies.dataset.mainBelt.records].find(item=>item.spkid===String(spkid));if(!record)return null;selected=`sbdb:${record.spkid}`;focusParent=null;smallBodySelected=record;q("[data-ds-level]").textContent=record.classification==="dwarf planet"?`Level 2 — ${l().dwarfPlanets}`:`Level 2 — ${l().mainBelt}`;renderSmallBodyInfo(record);return record;}
  function focusSelectedObject(){const position=selectedScenePosition();if(!position)return false;if(scaleContext==="solar"){const entity=dataSource.entities.getById(smallBodySelected?`deep-space-small-${smallBodySelected.spkid}`:`deep-space-${selected}`),radius=smallBodySelected?Math.max((smallBodySelected.diameterKm||2000)/2,8000):radiusFor(body(selected));if(entity){saved.lastObjectFocus=smallBodySelected?`sbdb:${smallBodySelected.spkid}`:selected;viewer.flyTo(entity,{duration:.8,offset:new Cesium.HeadingPitchRange(0,-.35,Math.max(radius*8,60000))});}return Boolean(entity);}const distance=scaleContext==="nearby"?Math.max(2e5,Nearby.sceneRadius(Math.max(nearbySelected?.distancePc*.02||.02,.02),mode)):Math.max(4e5,Coordinates.sceneRadiusKpc(Math.max((phase3Selected?.distanceKpc||.1)*.03,.1),mode,scaleContext==="milky-way"?"milky-way":"local-group"));saved.lastObjectFocus=scaleContext==="nearby"?(nearbySelected?.id||nearbySelected?.source_id):phase3Selected?.id;viewer.camera.flyTo({destination:new Cesium.Cartesian3(position.x,position.y,position.z+distance),duration:.8});return true;}
  function returnSolar(){++loadToken;setScaleControls("solar");clearScaleLayers();q("[data-ds-level]").textContent="Level 2 — Solar System";selected="sun";smallBodySelected=null;focusParent=null;renderAll();resetView();}
  function setCamera(kind){const height=mode==="scientific"?6e9:6.5e6;viewer.camera.cancelFlight();viewer.camera.flyTo({destination:new Cesium.Cartesian3(0,0,height),orientation:{heading:0,pitch:kind==="top"?-Math.PI/2:-Math.PI/3,roll:0},duration:.7});}
  function setNearbyCamera(radiusPc){const height=Nearby.sceneRadius(radiusPc,mode)*1.35;viewer.camera.cancelFlight();viewer.camera.flyTo({destination:new Cesium.Cartesian3(0,-height*.35,height),orientation:{heading:0,pitch:-Math.PI/3,roll:0},duration:.7});}
  function resetView(){viewer.trackedEntity=undefined;follow=false;if(scaleContext==="nearby"){setNearbyCamera(Nearby.CONFIG.find(x=>x.id===nearbyTier).radiusPc);renderNearbyInfo(nearbyCatalog.landmarks?.records?.find(x=>x.id==="sun")||nearbySelected);return;}if(scaleContext==="milky-way"){setPhase3Camera(20);selectPhase3(phase3Selected||MilkyWay.MilkyWayLayer.SUN);return;}if(scaleContext==="local-group"){setPhase3Camera(1500);selectPhase3(phase3Selected||LocalGroup.MILKY_WAY);return;}selected="sun";smallBodySelected=null;setCamera("inclined");renderInfo();}
  function onTick(){const now=performance.now();if(!lastTick)lastTick=now;const delta=Math.min(now-lastTick,250);lastTick=now;if(!paused&&!nearbyActive){solarTime.advance(delta*speed,"playback");updatePositions();}}
  function trapFocus(event){if(event.key==="Escape"){if(!q("[data-object-card]").hidden){event.preventDefault();return closeObjectCard();}return close();}if(event.key!=="Tab")return;const items=[...overlay.querySelectorAll('button:not([disabled]),select,input')].filter(el=>el.offsetParent!==null);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  function open(){
    if(active||!viewer)return;active=true;sourceParent=host.parentNode;sourceNext=host.nextSibling;saved={globe:viewer.scene.globe.show,atmosphere:viewer.scene.skyAtmosphere.show,maxZoom:viewer.scene.screenSpaceCameraController.maximumZoomDistance,zoomEnabled:viewer.scene.screenSpaceCameraController.enableZoom,focus:document.activeElement,camera:{position:Cesium.Cartesian3.clone(viewer.camera.positionWC),direction:Cesium.Cartesian3.clone(viewer.camera.directionWC),up:Cesium.Cartesian3.clone(viewer.camera.upWC)}};
    saved.layers=[...viewer.imageryLayers._layers].map((layer)=>[layer,layer.show]);saved.dataSources=Array.from({length:viewer.dataSources.length},(_,index)=>viewer.dataSources.get(index)).map((source)=>[source,source.show]);saved.earthRenderGeneration=global.PCSEarthRenderOwnership?.deactivateForDeepSpace?.();overlay.hidden=false;document.body.classList.add("deep-space-open");viewport.append(host);viewer.scene.globe.show=false;viewer.scene.skyAtmosphere.show=false;saved.layers.forEach(([layer])=>layer.show=false);saved.dataSources.forEach(([source])=>source.show=false);viewer.scene.screenSpaceCameraController.maximumZoomDistance=1e11;viewer.resize();
    dataSource=new Cesium.CustomDataSource("pcs-deep-space-phase-1");viewer.dataSources.add(dataSource);mainBeltLayer=new SmallBodies.MainBeltLayer(viewer,state=>positionFor(state.bodyId,state));nearbyCatalog=new Nearby.NearbyStarsCatalog();nearbyLayer=new Nearby.NearbyStarsLayer(viewer);milkyWayCatalog=new MilkyWay.MilkyWayCatalog();milkyWayLayer=new MilkyWay.MilkyWayLayer(viewer);localGroupCatalog=new LocalGroup.LocalGroupCatalog();localGroupLayer=new LocalGroup.LocalGroupLayer(viewer);scaleContext="solar";renderAll();resetView();lastTick=performance.now();tickRemover=viewer.clock.onTick.addEventListener(onTick);
    clickHandler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);clickHandler.setInputAction((movement)=>{const picked=viewer.scene.pick(movement.position),star=picked?.id?.nearbyStar,smallBody=picked?.id?.smallBody,phase3=picked?.id?.phase3Object,reconstruction=picked?.id?.phase3Reconstruction,id=picked?.id?.properties?.deepSpaceBodyId?.getValue?.(),smallSpkid=picked?.id?.properties?.smallBodySpkid?.getValue?.();if(star)renderNearbyInfo(star);else if(smallBody)renderSmallBodyInfo(smallBody);else if(smallSpkid)selectSmallBody(smallSpkid);else if(phase3)selectPhase3(phase3);else if(reconstruction){phase3Selected=ObjectCard.reconstruction(reconstruction);showObjectCard(phase3Selected);}else if(id)selectBody(id);},Cesium.ScreenSpaceEventType.LEFT_CLICK);setupPointerNavigation();q("[data-ds-close]").focus();
  }
  function close(){
    if(!active)return;active=false;++loadToken;setScaleControls("solar");viewer.camera.cancelFlight();disposePointerNavigation();if(tickRemover){tickRemover();tickRemover=null;}if(clickHandler){clickHandler.destroy();clickHandler=null;}mainBeltLayer?.dispose();mainBeltLayer=null;nearbyLayer?.dispose();nearbyLayer=null;nearbyCatalog?.unload();nearbyCatalog=null;milkyWayLayer?.dispose();milkyWayLayer=null;milkyWayCatalog?.unload();milkyWayCatalog=null;localGroupLayer?.dispose();localGroupLayer=null;localGroupCatalog?.unload();localGroupCatalog=null;viewer.trackedEntity=undefined;if(dataSource){viewer.dataSources.remove(dataSource,true);dataSource=null;}
    if(sourceNext&&sourceNext.parentNode===sourceParent)sourceParent.insertBefore(host,sourceNext);else sourceParent.append(host);viewer.scene.globe.show=saved.globe;viewer.scene.skyAtmosphere.show=saved.atmosphere;saved.layers?.forEach(([layer,show])=>layer.show=show);saved.dataSources?.forEach(([source,show])=>{if(!source.isDestroyed?.())source.show=show;});if(saved.camera)viewer.camera.setView({destination:saved.camera.position,orientation:{direction:saved.camera.direction,up:saved.camera.up}});global.PCSEarthRenderOwnership?.restoreAfterDeepSpace?.();viewer.scene.screenSpaceCameraController.maximumZoomDistance=saved.maxZoom;overlay.hidden=true;document.body.classList.remove("deep-space-open");viewer.resize();saved.focus?.focus?.();
  }
  function initialize(options){viewer=options.viewer;host=options.host;if(!overlay)setupOverlay();document.querySelector('[data-solar-target="deep-space"]')?.addEventListener("click",(event)=>{event.preventDefault();event.stopImmediatePropagation();open();},{capture:true});}
  const smallBodyProvider=Object.freeze({status:"catalog-derived",getObjects:()=>Promise.resolve(SmallBodies.dataset.mainBelt.records)}),cometEphemerisProvider=Object.freeze({status:"unavailable",getState:()=>null}),orbitUncertaintyProvider=Object.freeze({status:"unavailable",getUncertainty:()=>null});
  global.PCSDeepSpaceManager=Object.freeze({initialize,open,close,enterNearby,enterMilkyWay,enterLocalGroup,returnSolar,searchNearby,searchPhase3,setEpoch,isOpen:()=>active,debug:()=>({initialized:Boolean(viewer),viewerCount:document.querySelectorAll(".cesium-viewer").length,canvasCount:document.querySelectorAll("canvas").length,active,scaleContext,mode,epoch:displayEpoch().toISOString(),solarTime:solarTime.snapshot(),solarSolution,orbitCacheEntries:orbitCache.size,tickListenerActive:Boolean(tickRemover),pointerNavigationActive:Boolean(navigationAbort),nativeZoomEnabled:Boolean(viewer?.scene?.screenSpaceCameraController?.enableZoom),lastPointerZoom:saved.lastPointerZoom||null,lastObjectFocus:saved.lastObjectFocus||null,objectCardId:q("[data-object-card]")?.hidden?null:q("[data-object-card]")?.dataset.objectId||null,selected,smallBodySelected:smallBodySelected?.spkid||null,mainBelt:mainBeltLayer?.debug()||null,nearbyActive,nearbyTier,nearbySelected:nearbySelected?.primaryName||nearbySelected?.source_id||null,nearbySelectedMetadata:nearbySelectedDebug(),phase3Selected:phase3Selected?.canonicalName||null,nearby:nearbyLayer?.debug()||null,milkyWay:milkyWayLayer?.debug()||null,localGroup:localGroupLayer?.debug()||null}),smallBodyProvider,cometEphemerisProvider,orbitUncertaintyProvider});
})(window);
