const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const root=__dirname,read=name=>fs.readFileSync(path.join(root,name),"utf8");
function runtime(){const window={},context=vm.createContext({window,Date,Math,RangeError,Object,Map,Number,String,Boolean,Infinity});for(const name of ["solar-system-core.js","data/solar-system/normalized/small-bodies-sbdb.js","data/solar-system/normalized/comets-sbdb.js","small-body-catalog.js"])vm.runInContext(read(name),context);return window;}

test("Halley complete-orbit sampling closes the source-element path and preserves both apsides",()=>{const {PCSSolarSystemCometDataset:data,PCSSmallBodies:small}=runtime(),halley=data.records.find(record=>record.designation==="1P"),states=small.sampleFullOrbit(halley,{samples:360});assert.equal(states.length,361);assert.ok(states.every(state=>state.positionAu.length===3&&state.positionAu.every(Number.isFinite)));for(let axis=0;axis<3;axis+=1)assert.ok(Math.abs(states[0].positionAu[axis]-states.at(-1).positionAu[axis])<1e-10);const distances=states.map(state=>state.heliocentricDistanceAu);assert.ok(Math.abs(Math.min(...distances)-halley.elements.q)<1e-10);assert.ok(Math.abs(Math.max(...distances)-halley.elements.aphelionAu)<1e-10);assert.match(states[0].positionMode,/Complete source-element orbit path/);});

test("FIT ORBIT is generic, bounding-volume based, and has no Halley camera hack",()=>{const manager=read("deep-space.js");for(const token of ["function fitOrbit(target=smallBodySelected||selected)","CameraScale.boundingSphere(arrays)","CameraScale.fitDistance({radius:bounds.radius,fovY,aspectRatio,margin:1.28})","CameraScale.clipPlanes({range,radius:bounds.radius})","SmallBodies.sampleFullOrbit(object,{samples:360})","completeOrbit:true"])assert.ok(manager.includes(token),token);assert.doesNotMatch(manager,/Halley/);assert.doesNotMatch(manager,/1920|2560|3840|5120/);});

test("camera history restores the pre-selection state from empty space and Back",()=>{const manager=read("deep-space.js");assert.match(manager,/function pushCameraHistory\(reason\)/);assert.match(manager,/function restoreCameraHistory\(\)/);assert.match(manager,/else if\(!picked\)restoreCameraHistory\(\)/);assert.match(manager,/data-ds-back/);assert.match(manager,/cameraHistoryDepth:cameraHistory\.length/);assert.doesNotMatch(manager,/restoreCameraHistory[\s\S]{0,120}selected="sun"/);});

test("comet-orbit pointer fallback anchors the orbit center after the fit flight settles",()=>{const manager=read("deep-space.js");assert.match(manager,/cameraScaleIntent==="comet-orbit"&&lastOrbitFit/);assert.match(manager,/source:orbitId\?"orbit-center-after-line-rejection":"orbit-center"/);assert.match(manager,/completeOrbit:true,settled:false/);assert.match(manager,/lastOrbitFit\.settled=true/);});

test("responsive viewport excludes the visible data panel and expands when collapsed",()=>{const css=read("deep-space.css");assert.match(css,/--deep-space-panel-width:clamp\(320px,18vw,420px\)/);assert.match(css,/inset:0 calc\(var\(--deep-space-panel-width\) \+ 1\.6rem\) 0 0/);assert.match(css,/is-controls-collapsed \.deep-space-viewport\{right:0\}/);assert.match(css,/@media\(max-width:700px\)\{\.deep-space-viewport\{inset:0/);});

test("full-orbit controls preserve one Viewer and the four-language runtime",()=>{const manager=read("deep-space.js"),html=read("index.html"),copy=manager.match(/const ORBIT_UI_COPY=Object\.freeze\(\{([\s\S]*?)\n  \}\);/)?.[1]||"";assert.equal((copy.match(/fitOrbit:/g)||[]).length,4);assert.equal((copy.match(/searchPlaceholder:/g)||[]).length,4);assert.equal((manager.match(/new Cesium\.Viewer/g)||[]).length,0);assert.doesNotMatch(manager,/Math\.random|requestAnimationFrame|setInterval/);assert.ok(html.indexOf("astronomical-camera-scale.js")<html.indexOf("deep-space.js"));});
