const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const root=__dirname,read=name=>fs.readFileSync(path.join(root,name),"utf8");
function runtime(){const window={},context=vm.createContext({window,Date,Math,RangeError,Object,Map,Number,String,Boolean,Infinity});for(const name of ["solar-system-core.js","data/solar-system/normalized/interstellar-objects-horizons.js","interstellar-objects.js","unified-object-card.js"])vm.runInContext(read(name),context);return window;}

test("MPC identities and formal scientific classes are exact",()=>{const {PCSInterstellarObjectDataset:data}=runtime();assert.equal(data.recordCount,3);assert.deepEqual(Array.from(data.records,record=>record.id),["1I","2I","3I"]);assert.equal(data.records[0].officialDesignation,"1I/2017 U1 (ʻOumuamua)");assert.equal(data.records[0].provisionalDesignation,"A/2017 U1");assert.equal(data.records[0].objectClass,"Interstellar Object");assert.equal(data.records[1].officialDesignation,"2I/Borisov");assert.equal(data.records[1].provisionalDesignation,"C/2019 Q4");assert.equal(data.records[1].objectClass,"Interstellar Comet");assert.equal(data.records[2].officialDesignation,"3I/ATLAS");assert.equal(data.records[2].provisionalDesignation,"C/2025 N1");assert.equal(data.records[2].objectClass,"Interstellar Comet");});

test("every trajectory is hyperbolic, open, sourced, and non-periodic",()=>{const {PCSInterstellarObjectDataset:data,PCSInterstellarObjects:objects}=runtime();for(const record of data.records){assert.ok(record.elements.e>1);assert.ok(record.elements.a<0);assert.ok(record.elements.q>0);assert.match(record.orbitType,/Open hyperbolic/);assert.equal(record.originSystemStatus,"Unknown / unconstrained");assert.ok(record.samples.length>500);assert.notDeepEqual(Array.from(record.samples[0].slice(1,4)),Array.from(record.samples.at(-1).slice(1,4)));assert.equal(objects.trajectoryStates(record).length,record.samples.length);assert.ok(record.references.some(value=>value.includes("jpl")));assert.ok(record.knownLimitations.some(value=>/non-periodic|no return/i.test(value)));}});

test("Horizons Hermite states cover each known passage and perihelion",()=>{const {PCSInterstellarObjectDataset:data,PCSInterstellarObjects:objects}=runtime(),epochs={"1I":"2017-09-09T12:10:32Z","2I":"2019-12-08T13:16:05Z","3I":"2025-10-29T11:53:10Z"};for(const record of data.records){const state=objects.stateAt(record,epochs[record.id]);assert.ok(state);assert.equal(state.source,"NASA/JPL Horizons API");assert.ok(state.positionAu.every(Number.isFinite));assert.ok(Math.abs(state.heliocentricDistanceAu-record.elements.q)<2e-3,`${record.id} perihelion`);}});

test("observed, historical reconstruction, and ephemeris-derived segments stay distinct",()=>{const {PCSInterstellarObjectDataset:data,PCSInterstellarObjects:objects}=runtime();for(const record of data.records){const segments=objects.splitSamples(record);assert.ok(segments.reconstructed.length>1);assert.ok(segments.observed.length>1);assert.ok(segments.derived.length>1);assert.ok(segments.observed.every(sample=>Array.isArray(sample)));}});

test("search aliases include all requested forms without changing ATLAS record identity",()=>{const {PCSInterstellarObjects:objects}=runtime();for(const alias of ["ʻOumuamua","Oumuamua","1I","1I/2017 U1"])assert.equal(objects.search(alias).id,"1I");for(const alias of ["Borisov","2I","2I/Borisov"])assert.equal(objects.search(alias).id,"2I");for(const alias of ["3I/ATLAS","3I","ATLAS"])assert.equal(objects.search(alias).id,"3I");assert.equal(objects.search("C/2025 N1").officialDesignation,"3I/ATLAS");});

test("unified Object Cards expose interstellar provenance and limitations in four languages",()=>{const {PCSInterstellarObjectDataset:data,PCSInterstellarObjects:objects,PCSUnifiedObjectCard:cards}=runtime(),record=data.records[0],state=objects.stateAt(record,"2017-10-19T00:00:00Z"),card=cards.interstellar(record,state,"en");assert.equal(card.objectType,"Interstellar Object");assert.equal(card.interstellar.designation,"1I/2017 U1 (ʻOumuamua)");assert.match(card.interstellar.orbitType,/Open hyperbolic/);assert.match(card.interstellar.observationArc,/last observational epoch 2018-01-02/);assert.equal(card.interstellar.originSystem,"Unknown / unconstrained");assert.ok(card.knownLimitations.some(value=>/shape/i.test(value)));assert.ok(card.knownLimitations.some(value=>/outside the 2017-10-14 to 2018-01-02 observation arc/i.test(value)));for(const language of ["en","zh-TW","ja","ko"]){for(const key of ["interstellarDesignation","objectClass","discoverySurvey","discoveryDate","orbitType","hyperbolicExcess","perihelion","observationArc","trajectorySource","inboundDirection","outboundDirection","originSystem","nonGravitational"])assert.equal(typeof cards.COPY[language][key],"string",`${language}.${key}`);}});

test("runtime integrates one removable layer without another Viewer or canvas",()=>{const manager=read("deep-space.js"),layer=read("interstellar-objects.js"),html=read("index.html");assert.match(html,/interstellar-objects-horizons\.js/);assert.match(html,/interstellar-objects\.js/);assert.match(manager,/new Interstellar\.InterstellarLayer/);assert.match(manager,/interstellarLayer\?\.dispose\(\)/);assert.match(manager,/data-ds-interstellar/);assert.match(manager,/jumpToInterstellarPassage/);assert.doesNotMatch(layer,/new Cesium\.Viewer|createElement\(["']canvas|requestAnimationFrame|setInterval|Math\.random/);assert.doesNotMatch(manager,/new Cesium\.Viewer/);});
