const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const window={};let fetchImpl=()=>Promise.reject(new Error("unset"));vm.runInNewContext(fs.readFileSync(`${__dirname}/nearby-stars.js`,"utf8"),{window,Math,Object,AbortController,fetch:(...args)=>fetchImpl(...args)});const N=window.PCSNearbyStars;
test("pc and ly conversion is fixed and documented",()=>assert.ok(Math.abs(N.PC_TO_LY-3.261563777)<1e-10));
test("ICRS Cartesian axes and Galactic matrix are sane",()=>{assert.deepEqual(Array.from(N.icrsToCartesian(0,0,1)).map(x=>Math.round(x)),[1,0,0]);const g=N.icrsToGalactic(266.4051,-28.936175,1);assert.ok(g[0]>.9999&&Math.abs(g[1])<.001&&Math.abs(g[2])<.001);});
test("proper motion is bounded and never invents radial velocity",()=>{const p=N.propagate({ra:10,dec:20,pmra:100,pmdec:null,referenceEpoch:2016},2200);assert.equal(p.clamped,true);assert.match(p.method,/5D/);});
test("ICRS landmark vectors are transformed before scene mapping",()=>{const g=N.galacticCartesian({cartesianPc:[1,0,0],coordinateFrame:"heliocentric ICRS Cartesian"});assert.ok(Math.abs(g[0]+.0548755604)<1e-10);});
test("landmark metadata is merged onto matching catalog stars without duplicates",()=>{const out=N.mergeRecords([{source_id:"1",distancePc:2,cartesianPc:[1,0,0]}],[{source_id:"1",primaryName:"Known",distancePc:2},{source_id:"2",primaryName:"Other",distancePc:5,cartesianPc:[0,1,0]}],10);assert.equal(out.length,2);assert.equal(out[0].primaryName,"Known");});
test("all required architecture classes and tiers exist",()=>{for(const k of ["NearbyStarsCatalog","NearbyStarsLayer","NearbyStarsLODController","NearbyStarsSelectionController","NearbyStarsLabelController"])assert.equal(typeof N[k],"function");assert.deepEqual(Array.from(N.CONFIG,x=>x.radiusPc),[10,25,50,100]);});
test("catalog loader rejects missing and corrupt local files without permanent loading",async()=>{const c=new N.NearbyStarsCatalog("./");fetchImpl=async()=>({ok:false,status:404});await assert.rejects(c.load("10pc"),/catalog file missing/);fetchImpl=async()=>({ok:true,json:async()=>({bad:true})});await assert.rejects(c.load("10pc"),/catalog parse error/);c.unload();});
