const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=__dirname,read=name=>fs.readFileSync(path.join(root,name),"utf8"),json=name=>JSON.parse(read(name));
function browserDataset(file,key){const window={};vm.runInNewContext(read(file),{window,Object});return window[key];}
test("SS-02A-F promotion manifests and machine comparisons are all passing",()=>{for(const [manifestFile,evidenceFile,count] of [["data/solar-system/ephemeris-manifest.json","test-results/solar-system-ss02b/authoritative-position-comparison.json",46],["data/solar-system/small-body-manifest.json","test-results/solar-system-ss02c/authoritative-position-comparison.json",27],["data/solar-system/tno-manifest.json","test-results/solar-system-ss02d/authoritative-position-comparison.json",16],["data/solar-system/comet-manifest.json","test-results/solar-system-ss02e/authoritative-position-comparison.json",18]]){const manifest=json(manifestFile),evidence=json(evidenceFile);assert.equal(manifest.promotionStatus,"validated-promoted");assert.equal(manifest.validation.failures,0);assert.equal(evidence.failures,0);assert.equal(evidence.comparisons.length,count);assert.ok(evidence.comparisons.every(item=>item.pass));}});
test("SS-02 catalog registries have stable unique ownership",()=>{const small=browserDataset("data/solar-system/normalized/small-bodies-sbdb.js","PCSSolarSystemSmallBodyDataset"),tno=browserDataset("data/solar-system/normalized/tno-sbdb.js","PCSSolarSystemTnoDataset"),comets=browserDataset("data/solar-system/normalized/comets-sbdb.js","PCSSolarSystemCometDataset"),ids=[...small.dwarfPlanets,...small.mainBelt.records,...tno.records,...comets.records].map(item=>String(item.spkid));assert.equal(ids.length,new Set(ids).size);assert.equal(small.dwarfPlanets.length,5);assert.equal(small.mainBelt.records.length,5365);assert.equal(tno.records.length,7155);assert.equal(comets.records.length,9);});
test("SS-02F status is validated after every dataset gate",()=>{const status=json("data/solar-system/sync-status.json"),latest=Math.max(...status.datasets.map(item=>Date.parse(item.validatedAt)));assert.equal(status.state,"validated");assert.equal(status.datasets.length,4);assert.ok(Date.parse(status.lastSuccessfulSynchronization)>=latest);assert.equal(status.lastError,null);assert.match(status.fallbackPolicy,/Retain last validated/);});
test("Solar System documentation records final human production acceptance",()=>{const ss02=read("docs/SOLAR_SYSTEM_SS02.md"),audit=read("docs/SOLAR_SYSTEM_SS02_RELEASE_AUDIT.md");assert.match(ss02,/SS-02A–G completed/i);assert.match(ss02,/SS-02 frozen/i);assert.match(audit,/human visual confirmation received/i);assert.match(audit,/physical Mac trackpad.*open/is);assert.match(audit,/Deep Space Phase 4A.*authorized/is);});
test("release registry preserves frozen baselines while Milky Way is reopened",()=>{const releases=json("data/releases.json"),solar=releases.roadmap.find(item=>item.id==="solar-system-ss02"),foundation=releases.roadmap.find(item=>item.id==="v2.2.0-foundation"),milkyWay=releases.roadmap.find(item=>item.id==="deep-space-phase-3"),waiting=releases.roadmap.filter(item=>item.status==="waiting");assert.equal(solar.status,"completed");assert.match(solar.detail,/Human-approved/);assert.equal(foundation.status,"completed");assert.equal(milkyWay.status,"in-progress");assert.match(milkyWay.statusLabel.en,/Reopened.*Human Visual Review/);assert.ok(releases.releases[0].changed.some(item=>item.includes("Milky Way Scientific Scale Anchor")));assert.deepEqual(waiting.map(item=>item.id),["laniakea","observable-universe","cmb-360"]);assert.equal(releases.stableVersion,"v2.1.0");assert.equal(releases.currentStatus,"preview");});
test("SS-02G does not add another renderer or animation loop",()=>{const manager=read("deep-space.js"),pipeline=read("scripts/solar-system/sync-solar-system.mjs"),layers=["small-body-catalog.js","tno-catalog.js","comet-catalog.js"].map(read).join("\n");assert.doesNotMatch(manager,/new\s+Cesium\.Viewer|createElement\(["']canvas/);assert.doesNotMatch(pipeline,/requestAnimationFrame|setInterval|Math\.random/);assert.match(layers,/PointPrimitiveCollection/);});
