(function exposeTnoCatalog(global){
  "use strict";
  const dataset=global.PCSSolarSystemTnoDataset,SmallBodies=global.PCSSmallBodies;
  if(!dataset||!SmallBodies)return;
  class TnoLayer{
    constructor(viewer,positionMapper){this.viewer=viewer;this.positionMapper=positionMapper;this.collection=viewer.scene.primitives.add(new Cesium.PointPrimitiveCollection());this.records=[];this.points=[];this.mode="exhibition";this.epoch=new Date();this.epochSupported=SmallBodies.isEpochSupported(this.epoch);this.lod="far";this.pendingEpoch=null;this.updateTargetEpoch=null;this.updateCursor=0;this.completedEpochUpdates=0;this.moveRemover=viewer.camera.moveEnd.addEventListener(()=>this.updateLod());}
    limit(){return dataset.lod[this.lod]||dataset.lod.far;}
    determineLod(){const distance=Cesium.Cartesian3.magnitude(this.viewer.camera.positionWC),thresholds=this.mode==="scientific"?[1.5e10,7e9]:[6e6,3.5e6];return distance>thresholds[0]?"far":distance>thresholds[1]?"medium":"near";}
    updateLod(force){const next=this.determineLod();if(!force&&next===this.lod)return;this.lod=next;const limit=this.limit();this.points.forEach((point,index)=>{point.show=this.epochSupported&&index<limit;});this.viewer.scene.requestRender();}
    load(records,epoch,mode="exhibition"){this.collection.removeAll();this.records=[...records];this.epoch=new Date(epoch);this.epochSupported=SmallBodies.isEpochSupported(this.epoch);this.mode=mode;this.pendingEpoch=null;this.updateTargetEpoch=null;this.updateCursor=0;this.points=this.records.map((record,index)=>{const state=SmallBodies.stateAt(record,this.epoch),position=state?this.positionMapper(state):null;if(!position)return null;const diameter=record.diameterKm,pixelSize=Number.isFinite(diameter)?Math.max(2,Math.min(7,2+Math.log10(diameter+1))):index<64?3:2;return this.collection.add({position,pixelSize,color:Cesium.Color.fromCssColorString(index<64?"#a9d7ee":"#6f9ebd").withAlpha(.8),show:false,id:{smallBody:record,smallBodyLayer:"tno-known-catalog"}});}).filter(Boolean);this.updateLod(true);return this.debug();}
    scheduleEpoch(epoch){const target=new Date(epoch),supported=SmallBodies.isEpochSupported(target);this.epochSupported=supported;if(!supported){this.epoch=target;this.pendingEpoch=null;this.updateTargetEpoch=null;this.updateCursor=0;this.points.forEach(point=>{point.show=false;});this.viewer.scene.requestRender();return target;}this.pendingEpoch=target;return this.pendingEpoch;}
    processEpochUpdate(maxRecords=256){if(!this.updateTargetEpoch&&this.pendingEpoch){this.updateTargetEpoch=this.pendingEpoch;this.pendingEpoch=null;this.updateCursor=0;}if(!this.updateTargetEpoch)return 0;const chunk=Math.max(1,Math.floor(maxRecords)),start=this.updateCursor,limit=Math.min(this.records.length,start+chunk),target=this.updateTargetEpoch;for(;this.updateCursor<limit;this.updateCursor+=1){const state=SmallBodies.stateAt(this.records[this.updateCursor],target),point=this.points[this.updateCursor];if(point&&state)point.position=this.positionMapper(state);}if(this.updateCursor>=this.records.length){this.epoch=target;this.updateTargetEpoch=null;this.updateCursor=0;this.completedEpochUpdates+=1;this.updateLod(true);}this.viewer.scene.requestRender();return limit-start;}
    updateEpoch(epoch){this.scheduleEpoch(epoch);while(this.updateTargetEpoch||this.pendingEpoch)this.processEpochUpdate(Math.max(1,this.records.length));}
    setMode(mode){this.mode=mode;this.load(this.records,this.epoch,mode);}
    unload(){this.records=[];this.points=[];this.pendingEpoch=null;this.updateTargetEpoch=null;this.updateCursor=0;this.collection.removeAll();}
    dispose(){this.moveRemover?.();this.moveRemover=null;if(this.collection){this.viewer.scene.primitives.remove(this.collection);this.collection=null;}this.records=[];this.points=[];this.pendingEpoch=null;this.updateTargetEpoch=null;this.updateCursor=0;}
    debug(){return Object.freeze({datasetId:dataset.datasetId,knownCatalogRecords:this.records.length,pointCount:this.points.length,visibleCount:this.points.filter(point=>point.show).length,lod:this.lod,epochSupported:this.epochSupported,deployedEpochRange:SmallBodies.deployedEpochRange,deterministic:true,epochUpdatePending:Boolean(this.pendingEpoch||this.updateTargetEpoch),epochUpdateCursor:this.updateCursor,completedEpochUpdates:this.completedEpochUpdates,selection:dataset.selection,representativePopulation:dataset.representativePopulation});}
  }
  global.PCSTnoCatalog=Object.freeze({dataset,TnoLayer});
})(window);
