#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {ADAPTERS} from "./adapters.mjs";
import {ingestRecords,sha256} from "./catalog-core.mjs";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."),read=relative=>JSON.parse(fs.readFileSync(path.join(root,relative),"utf8")),sources=read("data/catalogs/provenance/source-registry.json"),production=read("data/catalogs/production/known-astronomical-objects.json"),manifest=read("data/catalogs/manifests/phase-a.json");
const fixture=overrides=>({pcsObjectId:"pcs:fixture:alpha",officialName:"Fixture Alpha",commonName:null,aliases:[],objectClass:"stellar-object",objectSubtype:"test fixture",catalogIdentifiers:[{catalog:"FIXTURE",identifier:"A"}],raDeg:10,decDeg:-10,coordinateFrame:"ICRS",coordinateEpoch:"J2000",distance:null,distanceLower:null,distanceUpper:null,distanceUnit:null,distanceMethod:null,parallaxMas:null,properMotionRaMasYr:null,properMotionDecMasYr:null,radialVelocityKmS:null,redshift:null,physicalSize:null,angularSize:null,mass:null,massMethod:null,age:null,temperatureK:null,spectralType:null,hostStructure:null,parentObject:null,associatedObjects:[],discoveryDate:null,discoveryMethod:null,observationStatus:"TEST_FIXTURE_ONLY",evidenceClass:"CATALOG-DERIVED",scientificFidelity:"LB",wavelengths:[],geometryStatus:"MEASURED_POSITION",lastUpdated:"2026-08-14",dataSources:["cds-simbad-tap"],researchReferences:["TEST_FIXTURE_ONLY"],knownLimitations:["Not production astronomical data"],...overrides});
const fixtureResult=ingestRecords([fixture({}),fixture({pcsObjectId:"pcs:fixture:alpha-alternate",officialName:"Fixture Alpha Alternate"}),fixture({pcsObjectId:"pcs:fixture:beta",officialName:"Fixture Beta",catalogIdentifiers:[{catalog:"FIXTURE",identifier:"B"}],parentObject:"pcs:fixture:alpha",associatedObjects:["pcs:fixture:missing"]}),fixture({pcsObjectId:"pcs:fixture:invalid",officialName:""})],{sourceRegistry:sources,sourceId:"cds-simbad-tap",retrievedAt:"2026-08-14"});
const online=process.argv.includes("--online"),capabilities=[];
if(online)for(const adapter of Object.values(ADAPTERS)){const url=adapter.protocol==="tap"?`${adapter.endpoint}/capabilities`:`${adapter.endpoint}/_services.html`;try{const response=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(30000)});await response.arrayBuffer();capabilities.push({adapterId:adapter.adapterId,url,status:response.status,ok:response.ok});}catch(error){capabilities.push({adapterId:adapter.adapterId,url,status:null,ok:false,error:error.message});}}
const adapterSources=new Set(Object.values(ADAPTERS).map(adapter=>adapter.sourceId)),registrySources=new Set(sources.sources.map(source=>source.sourceId));
const report={schemaVersion:"pcs-known-object-phase-a-validation-v1",generatedAt:new Date().toISOString(),phase:"A",pass:production.objectCount===0&&manifest.productionCounts.imported===0&&[...adapterSources].every(id=>registrySources.has(id))&&fixtureResult.importedCount===2&&fixtureResult.rejectedCount===1&&fixtureResult.unresolvedCount===1&&(!online||capabilities.every(item=>item.ok)),productionCounts:manifest.productionCounts,architectureValidationFixture:{scope:"NON_PRODUCTION_TEST_FIXTURE",input:fixtureResult.inputCount,imported:fixtureResult.importedCount,rejected:fixtureResult.rejectedCount,unresolved:fixtureResult.unresolvedCount},sourceCapabilityCount:Object.values(ADAPTERS).length,sourceRegistryRecordCount:sources.sources.length,sourceRegistryChecksum:sha256(sources),schemaChecksum:sha256(read("data/catalogs/schemas/pcs-astronomical-object-v1.schema.json")),capabilities,scientificBoundary:"No Phase B-E astronomical object rows were imported or rendered"};
const output=path.join(root,"test-results/known-astronomical-objects-phase-a");fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,"validation-report.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
